version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aspire:
        patterns:
          - "Aspire.*"
    open-pull-requests-limit: 10
