// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Aspire.Hosting.ApplicationModel;

/// <summary>
/// Curated set of DocumentDB versions known to this build of the package. Each member maps to
/// a published <c>documentdb-local</c> container tag of the form <c>pgN-X.Y.Z</c>.
/// </summary>
/// <remarks>
/// <para>
/// This enum is <b>append-only</b>. Members are added by the
/// <c>check-documentdb-version</c> workflow when a new upstream version is published.
/// Existing members and their explicit numeric values must never be renamed, removed, or
/// reordered, as that would be a binary breaking change for callers compiled against earlier
/// versions of this package. Members that should no longer be used are marked
/// <see cref="ObsoleteAttribute"/> rather than removed.
/// </para>
/// <para>
/// Use with <see cref="Aspire.Hosting.DocumentDBBuilderExtensions.WithDocumentDBVersion"/> to
/// pin a specific version. Use <see cref="DocumentDBVersions"/> to enumerate all known versions
/// or read the latest version known to this build.
/// </para>
/// </remarks>
public enum DocumentDBVersion
{
    // <auto-generated-versions-start>
    // APPEND-ONLY. Numeric values are explicit and frozen for binary stability.
    // Updated by .github/workflows/check-documentdb-version.yml.

    /// <summary>DocumentDB <c>0.109.0</c>.</summary>
    V0_109_0 = 1,

    /// <summary>DocumentDB <c>0.110.0</c>.</summary>
    V0_110_0 = 2,

    /// <summary>DocumentDB <c>0.111.0</c>.</summary>
    V0_111_0 = 3,

    /// <summary>DocumentDB <c>0.112.0</c>.</summary>
    V0_112_0 = 4,

    /// <summary>DocumentDB <c>0.113.0</c>.</summary>
    V0_113_0 = 5,

    /// <summary>DocumentDB <c>0.114.0</c>.</summary>
    V0_114_0 = 6,

    // <auto-generated-versions-end>
}

/// <summary>
/// Selects which PostgreSQL major version of the <c>documentdb-local</c> container image to use.
/// </summary>
/// <remarks>
/// Upstream publishes the same DocumentDB version against multiple PostgreSQL backend versions.
/// Use with <see cref="Aspire.Hosting.DocumentDBBuilderExtensions.WithPostgresVersion"/> to select
/// a non-default backend. Adding new variants (for example <c>Pg18</c>) is intentionally a manual
/// code change that requires review.
/// </remarks>
public enum DocumentDBPostgresVersion
{
    /// <summary>PostgreSQL 15 backend (<c>pg15-</c> tag prefix).</summary>
    Pg15 = 15,

    /// <summary>PostgreSQL 16 backend (<c>pg16-</c> tag prefix).</summary>
    Pg16 = 16,

    /// <summary>PostgreSQL 17 backend (<c>pg17-</c> tag prefix). Default.</summary>
    Pg17 = 17,
}

/// <summary>
/// String constants and lookup helpers for the DocumentDB versions known to this build of the
/// package.
/// </summary>
/// <remarks>
/// Per-version constants (for example <see cref="V0_109_0"/>) are stable strings and may safely
/// be exposed as <see langword="const"/>. <see cref="Latest"/> is intentionally a property — not
/// a <see langword="const"/> — so consumers re-resolve it after a NuGet upgrade rather than
/// inlining the old value at compile time.
/// </remarks>
public static class DocumentDBVersions
{
    // <auto-generated-versions-start>
    // Per-version string constants are stable forever once shipped (safe as `const`).
    // Updated by .github/workflows/check-documentdb-version.yml.

    /// <summary>DocumentDB version string <c>0.109.0</c>.</summary>
    public const string V0_109_0 = "0.109.0";

    /// <summary>DocumentDB version string <c>0.110.0</c>.</summary>
    public const string V0_110_0 = "0.110.0";

    /// <summary>DocumentDB version string <c>0.111.0</c>.</summary>
    public const string V0_111_0 = "0.111.0";

    /// <summary>DocumentDB version string <c>0.112.0</c>.</summary>
    public const string V0_112_0 = "0.112.0";

    /// <summary>DocumentDB version string <c>0.113.0</c>.</summary>
    public const string V0_113_0 = "0.113.0";

    /// <summary>DocumentDB version string <c>0.114.0</c>.</summary>
    public const string V0_114_0 = "0.114.0";

    // <auto-generated-versions-end>

    /// <summary>
    /// All DocumentDB versions known to this build of the package, sorted ascending by
    /// numeric semantic version. The order of this list is part of the contract:
    /// <c>All[All.Count - 1]</c> is always the newest known version.
    /// </summary>
    /// <remarks>
    /// The returned instance is a read-only wrapper that cannot be downcast to a mutable
    /// array. This protects <see cref="Latest"/> (which reads from this list) from being
    /// silently changed at runtime.
    /// </remarks>
    public static IReadOnlyList<string> All { get; } = Array.AsReadOnly(new[]
    {
        // <auto-generated-versions-start>
        V0_109_0,
        V0_110_0,
        V0_111_0,
        V0_112_0,
        V0_113_0,
        V0_114_0,

        // <auto-generated-versions-end>
    });

    /// <summary>
    /// The newest DocumentDB version known to <b>this build</b> of the package. This is the
    /// version applied by default when no explicit version is selected via
    /// <see cref="Aspire.Hosting.DocumentDBBuilderExtensions.WithDocumentDBVersion"/>.
    /// </summary>
    /// <remarks>
    /// This value reflects the latest version this package was built against, not the latest
    /// upstream release at runtime. Upgrade the NuGet package to pick up newer upstream versions.
    /// Exposed as a property so consumers re-resolve it after upgrading the package, rather than
    /// inlining the value at compile time as a <see langword="const"/> would do.
    /// </remarks>
    public static string Latest => All[All.Count - 1];

    internal static string ToVersionString(DocumentDBVersion version) => version switch
    {
        // <auto-generated-versions-start>
        DocumentDBVersion.V0_109_0 => V0_109_0,
        DocumentDBVersion.V0_110_0 => V0_110_0,
        DocumentDBVersion.V0_111_0 => V0_111_0,
        DocumentDBVersion.V0_112_0 => V0_112_0,
        DocumentDBVersion.V0_113_0 => V0_113_0,
        DocumentDBVersion.V0_114_0 => V0_114_0,

        // <auto-generated-versions-end>
        _ => throw new ArgumentOutOfRangeException(nameof(version), version, "Unknown DocumentDB version."),
    };
}
