// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Globalization;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.DocumentDB;
using Aspire.Hosting.Lifecycle;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;

namespace Aspire.Hosting;

/// <summary>
/// Provides extension methods for adding DocumentDB resources to an <see cref="IDistributedApplicationBuilder"/>.
/// </summary>
public static class DocumentDBBuilderExtensions
{
    private sealed class OpenTelemetryEnvironmentConfigurationAnnotation : IResourceAnnotation
    {
        public bool MetricsEnabled { get; set; }
    }

    // default internal port is 10260.
    private const int DefaultContainerPort = 10260;
    // default PostgreSQL coordinator port inside the documentdb-local container.
    private const int DefaultPostgresContainerPort = 9712;
    private const string DefaultHealthCheckDatabaseName = "admin";
    private static readonly Version OpenTelemetryConfigurationAffectedVersion = new(0, 116, 0);

    private const string UserEnvVarName = "USERNAME";
    private const string PasswordEnvVarName = "PASSWORD";
    private const string LogLevelEnvVarName = "LOG_LEVEL";
    private const string InitDataPathEnvVarName = "INIT_DATA_PATH";
    private const string SkipInitDataEnvVarName = "SKIP_INIT_DATA";
    private const string CertPathEnvVarName = "CERT_PATH";
    private const string KeyFileEnvVarName = "KEY_FILE";
    private const string EnableTelemetryEnvVarName = "ENABLE_TELEMETRY";
    private const string OtelMetricsEnabledEnvVarName = "OTEL_METRICS_ENABLED";
    private const string OtelExporterOtlpMetricsEndpointEnvVarName = "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT";
    private const string OtelExporterOtlpMetricsTimeoutEnvVarName = "OTEL_EXPORTER_OTLP_METRICS_TIMEOUT";
    private const string OtelMetricExportIntervalEnvVarName = "OTEL_METRIC_EXPORT_INTERVAL";
    private const string OtelServiceNameEnvVarName = "OTEL_SERVICE_NAME";
    private const string OtelServiceVersionEnvVarName = "OTEL_SERVICE_VERSION";
    private const string OwnerEnvVarName = "OWNER";
    private const string DataPathEnvVarName = "DATA_PATH";
    private const string DisableExtendedRumEnvVarName = "DISABLE_EXTENDED_RUM";
    private const string CreateUserEnvVarName = "CREATE_USER";
    private const string AllowExternalConnectionsEnvVarName = "ALLOW_EXTERNAL_CONNECTIONS";

    private const string DefaultMountedDataPath = "/data";
    private const string InitDataMountPath = "/init_doc_db.d";
    private const string DefaultGatewayConfigurationPath = "/home/documentdb/gateway/pg_documentdb_gw";
    private const string DefaultOpenTelemetryServiceName = "documentdb_gateway";
    private const string OpenTelemetryEnvironmentConfiguration = """
        {
          "NodeHostName": "localhost",
          "BlockedRolePrefixes": [
            "documentdb",
            "citus",
            "pg",
            "internal_role"
          ],
          "PostgresPort": 9712,
          "GatewayListenPort": 10260,
          "HostConfigurationWatchIntervalMs": 1000,
          "CertificateOptions": {
            "CertType": "PemAutoGenerated"
          },
          "UseLocalHost": false
        }
        """;

    /// <summary>
    /// Adds a DocumentDB resource to the application model. A container is used for local development.
    /// </summary>
    /// <remarks>
    /// This resource includes a built-in health check. When this resource is referenced as a dependency
    /// using the <see cref="ResourceBuilderExtensions.WaitFor{T}(IResourceBuilder{T}, IResourceBuilder{IResource})"/>
    /// extension method then the dependent resource will wait until the DocumentDB server responds to ping.
    /// This version of the package defaults to the <inheritdoc cref="DocumentDBContainerImageTags.Tag"/> tag of the <inheritdoc cref="DocumentDBContainerImageTags.Image"/> container image.
    /// </remarks>
    /// <param name="builder">The <see cref="IDistributedApplicationBuilder"/>.</param>
    /// <param name="name">The name of the resource. This name will be used as the connection string name when referenced in a dependency.</param>
    /// <param name="port">The host port for DocumentDB.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb", port: 10260);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> AddDocumentDB(this IDistributedApplicationBuilder builder, [ResourceName] string name, int? port)
        => AddDocumentDB(builder, name, port, null, null);

    /// <summary>
    /// <inheritdoc cref="AddDocumentDB(IDistributedApplicationBuilder, string, int?)"/>
    /// </summary>
    /// <param name="builder">The <see cref="IDistributedApplicationBuilder"/>.</param>
    /// <param name="name">The name of the resource. This name will be used as the connection string name when referenced in a dependency.</param>
    /// <param name="port">The host port for DocumentDB.</param>
    /// <param name="userName">A parameter that contains the DocumentDB server user name, or <see langword="null"/> to use a default value.</param>
    /// <param name="password">A parameter that contains the DocumentDB server password, or <see langword="null"/> to use a generated password.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// // Minimal usage with generated credentials:
    /// var server = builder.AddDocumentDB("documentdb");
    /// var database = server.AddDatabase("mydb");
    ///
    /// // With custom credentials:
    /// var user = builder.AddParameter("db-user");
    /// var pass = builder.AddParameter("db-pass", secret: true);
    /// var securedServer = builder.AddDocumentDB("documentdb", userName: user, password: pass);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> AddDocumentDB(this IDistributedApplicationBuilder builder,
        string name,
        int? port = null,
        IResourceBuilder<ParameterResource>? userName = null,
        IResourceBuilder<ParameterResource>? password = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(name);

        var passwordParameter = password?.Resource ?? ParameterResourceBuilderExtensions.CreateDefaultPasswordParameter(builder, $"{name}-password", special: false);

        var DocumentDBContainer = new DocumentDBServerResource(name, userName?.Resource, passwordParameter);

        string? connectionString = null;

        builder.Eventing.Subscribe<ConnectionStringAvailableEvent>(DocumentDBContainer, async (@event, ct) =>
        {
            connectionString = await DocumentDBContainer.ConnectionStringExpression.GetValueAsync(ct).ConfigureAwait(false)
                ?? throw new DistributedApplicationException($"ConnectionStringAvailableEvent was published for the '{DocumentDBContainer.Name}' resource but the connection string was null.");
        });

        var healthCheckKey = $"{name}_check";
        // Use a database-scoped check so the MongoDB health check package executes a ping command.
        IMongoDatabase? database = null;
        builder.Services.AddHealthChecks()
            .AddMongoDb(
                _ => database ??=
                    new MongoClient(connectionString ?? throw new InvalidOperationException("Connection string is unavailable"))
                        .GetDatabase(DefaultHealthCheckDatabaseName),
                name: healthCheckKey);

        return builder
            .AddResource(DocumentDBContainer)
            .WithEndpoint(port: port, targetPort: DefaultContainerPort, name: DocumentDBServerResource.PrimaryEndpointName)
            .WithImage(DocumentDBContainerImageTags.Image, DocumentDBContainerImageTags.Tag)
            .WithImageRegistry(DocumentDBContainerImageTags.Registry)
            .WithEnvironment(context =>
            {
                context.EnvironmentVariables[UserEnvVarName] = DocumentDBContainer.UserNameReference;
                context.EnvironmentVariables[PasswordEnvVarName] = DocumentDBContainer.PasswordParameter!;
            })
            .WithHealthCheck(healthCheckKey)
            .SubscribeMinimumPgVariantImageGuard()
            .InstallImageCompatibilityCheckpoints();
    }

    /// <summary>
    /// What this package knows about the container image a DocumentDB resource will run.
    /// </summary>
    /// <param name="Exists">Whether the resource carries a <see cref="ContainerImageAnnotation"/> at all.</param>
    /// <param name="Curated">
    /// Whether the image is the curated <see cref="DocumentDBContainerImageTags.Image"/> with a tag
    /// this build recognises. Only then do <paramref name="PostgresVariant"/> and
    /// <paramref name="KnownVersion"/> carry a value, and only then does a version floor apply.
    /// </param>
    /// <param name="Image">The repository as the annotation spells it, for diagnostics.</param>
    /// <param name="Tag">The tag as the annotation spells it, for diagnostics.</param>
    /// <param name="PostgresVariant">The PostgreSQL major version of a curated tag.</param>
    /// <param name="KnownVersion">The DocumentDB version of a curated tag.</param>
    private readonly record struct DocumentDBEffectiveImage(
        bool Exists,
        bool Curated,
        string? Image,
        string? Tag,
        int PostgresVariant,
        Version? KnownVersion);

    /// <summary>
    /// Resolves what this package knows about the container image <paramref name="resource"/> will
    /// run: the sealed image when a run has sealed one, and the live model otherwise.
    /// </summary>
    /// <remarks>
    /// Every version-dependent decision goes through this method, so making the seal the authority
    /// here is what makes all of them judge the image DCP will really launch rather than whatever
    /// the model happens to say at the moment they run. Outside a run no seal is ever taken and
    /// this is exactly <see cref="ResolveModelImage"/> — a publish reads the model at serialization
    /// time, which is the only image a publish has.
    /// </remarks>
    private static DocumentDBEffectiveImage ResolveEffectiveImage(IResource resource) =>
        resource.Annotations.OfType<DocumentDBImageSealAnnotation>().LastOrDefault() is { } seal
            ? seal.Image
            : ResolveModelImage(resource);

    /// <summary>
    /// Resolves what this package knows about the container image <paramref name="resource"/> will
    /// run, from the image annotation that is effective now.
    /// </summary>
    /// <remarks>
    /// The last <see cref="ContainerImageAnnotation"/> is the effective one, which is what makes
    /// the documented "last call wins" precedence hold for every caller of this method. Only the
    /// image name decides whether the curated matrix applies: a private mirror of the official
    /// image is still the official image, while a fork publishing under its own name decides its
    /// own matrix regardless of registry. A tag outside the strict <c>pg{NN}-X.Y.Z</c> grammar —
    /// including the <see langword="null"/> tag a digest pin leaves behind — carries no version,
    /// so no floor is enforced on it.
    /// </remarks>
    private static DocumentDBEffectiveImage ResolveModelImage(IResource resource)
    {
        var image = resource.Annotations.OfType<ContainerImageAnnotation>().LastOrDefault();

        if (image is null)
        {
            return default;
        }

        if (!string.Equals(image.Image, DocumentDBContainerImageTags.Image, StringComparison.Ordinal) ||
            !DocumentDBContainerImageTags.TryParseDocumentDBTag(image.Tag, out var pg, out var version))
        {
            return new(true, false, image.Image, image.Tag, 0, null);
        }

        return new(true, true, image.Image, image.Tag, pg, version);
    }

    /// <summary>
    /// The unpublished-variant floor, stated once and evaluated against one effective image.
    /// </summary>
    /// <returns>
    /// The failure to raise, or <see langword="null"/> when the image satisfies the floor or its
    /// version is not known.
    /// </returns>
    private static InvalidOperationException? DescribeUnpublishedPostgresVariant(
        IResource resource,
        DocumentDBEffectiveImage image)
    {
        if (image is not { Curated: true, KnownVersion: { } docVersion })
        {
            return null;
        }

        if (!DocumentDBContainerImageTags.MinimumVersionByPgVariant.TryGetValue(image.PostgresVariant, out var minimum) ||
            docVersion >= minimum)
        {
            return null;
        }

        return new InvalidOperationException(
            $"DocumentDB resource '{resource.Name}' resolves to image tag " +
            $"'{image.Tag}', but upstream only publishes pg{image.PostgresVariant} images from " +
            $"DocumentDB v{minimum} onwards. That tag does not exist on " +
            $"{DocumentDBContainerImageTags.Registry}/{DocumentDBContainerImageTags.Image}, " +
            $"so starting the resource would fail with an opaque manifest-not-found error. " +
            $"Recovery: pair '.WithPostgresVersion(DocumentDBPostgresVersion.Pg{image.PostgresVariant})' with " +
            $"DocumentDB v{minimum} or newer, or choose a PostgreSQL variant that exists " +
            $"for v{docVersion}.");
    }

    /// <summary>
    /// The <see cref="WithPostgresEndpoint"/> credential floor, stated once and evaluated against
    /// one effective image.
    /// </summary>
    /// <remarks>
    /// Whether the floor applies is read from the model rather than remembered at
    /// <see cref="WithPostgresEndpoint"/> time, so a checkpoint that judges the final image judges
    /// the final endpoint set with it.
    /// </remarks>
    private static InvalidOperationException? DescribePostgresEndpointFloor(
        IResource resource,
        DocumentDBEffectiveImage image)
    {
        if (image is not { Curated: true, KnownVersion: { } docVersion } ||
            docVersion >= DocumentDBContainerImageTags.MinimumPostgresEndpointVersion ||
            !PublishesPostgresEndpoint(resource))
        {
            return null;
        }

        return new InvalidOperationException(
            $"DocumentDB resource '{resource.Name}' is configured with image tag " +
            $"'{image.Tag}', but WithPostgresEndpoint() requires DocumentDB " +
            $"v{DocumentDBContainerImageTags.MinimumPostgresEndpointVersion} or later. " +
            $"Earlier images hard-code the PostgreSQL admin credentials to " +
            $"'docdb_admin'/'Admin100', so the Aspire-generated postgresql:// connection " +
            $"string would silently fail to authenticate. Recovery: chain " +
            $"'.WithImageTag(\"pg{{NN}}-{DocumentDBContainerImageTags.MinimumPostgresEndpointVersion}\")' " +
            $"(or newer) after AddDocumentDB(...). See " +
            $"https://github.com/microsoft/azure-databases-aspire/issues/71.");
    }

    /// <summary>
    /// Every hard image-compatibility floor this package enforces, evaluated together against the
    /// image the resource will actually run as the model now stands.
    /// </summary>
    /// <remarks>
    /// The variant floor is judged first, matching the order the two subscriptions are registered
    /// in, so a tag that breaks both rules reports the same failure it always has.
    /// </remarks>
    private static InvalidOperationException? DescribeIncompatibleImage(IResource resource)
    {
        var image = ResolveEffectiveImage(resource);

        return DescribeUnpublishedPostgresVariant(resource, image)
            ?? DescribePostgresEndpointFloor(resource, image);
    }

    /// <summary>
    /// Whether the resource publishes the PostgreSQL coordinator endpoint, which is what makes the
    /// credential floor apply to it.
    /// </summary>
    private static bool PublishesPostgresEndpoint(IResource resource) =>
        resource.Annotations.OfType<EndpointAnnotation>()
            .Any(endpoint => endpoint.Name == DocumentDBServerResource.PostgresEndpointName);

    /// <summary>
    /// The image and build origin a DocumentDB resource was sealed with, captured once per run at
    /// the last phase that is guaranteed to precede DCP's container preparation.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="Reference"/> is composed by <c>ResourceExtensions.TryGetContainerImageName</c>,
    /// which is the very method <c>ContainerCreator.PrepareObjects()</c> calls to fill the DCP
    /// container spec. Recording that string rather than the annotation's parts means the seal is
    /// literally what DCP snapshots, including the <c>registry/</c> prefix, the <c>@sha256:</c>
    /// form a digest pin takes, and the built-image name a Dockerfile origin substitutes.
    /// </para>
    /// <para>
    /// <see cref="BuildOrigin"/> holds the resource's <see cref="DockerfileBuildAnnotation"/>s by
    /// identity and in order, because that annotation is what decides whether
    /// <c>TryGetContainerImageName</c> returns the built image instead of the curated one, and
    /// whether the resource publishes <c>build</c> instead of <c>image</c>. Adding, removing or
    /// replacing one after the seal changes which image runs even when the composed reference
    /// happens to be spelled the same, so identity is compared rather than value.
    /// </para>
    /// </remarks>
    private sealed class DocumentDBImageSealAnnotation : IResourceAnnotation
    {
        public required string? Reference { get; init; }

        public required DocumentDBEffectiveImage Image { get; init; }

        public required DockerfileBuildAnnotation[] BuildOrigin { get; init; }
    }

    /// <summary>
    /// Seals the image of every DocumentDB resource in the model, once per application, at the
    /// latest phase that still precedes DCP.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>BeforeStartAsync</c> rather than a <see cref="BeforeStartEvent"/> subscription because
    /// the two are not interchangeable in ordering. Aspire's <c>ExecuteBeforeStartHooksAsync</c>
    /// publishes <see cref="BeforeStartEvent"/> to every subscriber first and only then runs the
    /// lifecycle hooks, so a hook is strictly later than <em>every</em>
    /// <see cref="BeforeStartEvent"/> subscriber — including ones an app host registers after
    /// <c>AddDocumentDB</c>, which is precisely the position this package cannot outrun by
    /// subscribing. It is still earlier than <c>DcpExecutor.RunApplicationAsync</c>, whose
    /// <c>ContainerCreator.PrepareObjects()</c> is where the image is snapshotted into the DCP
    /// container spec. That makes the hook the one point that is after all normal model building
    /// and before anything reads the image.
    /// </para>
    /// <para>
    /// Only a run is sealed. In a publish DCP never runs, no container spec exists, and the
    /// manifest is written from the model at serialization time — so the manifest checkpoint has
    /// to keep judging the live model, and sealing would make it judge an image that is not the
    /// one being published.
    /// </para>
    /// </remarks>
#pragma warning disable CS0618 // The lifecycle-hook phase has no eventing equivalent that runs after every BeforeStartEvent subscriber.
    private sealed class DocumentDBImageSealLifecycleHook(DistributedApplicationExecutionContext executionContext)
        : Lifecycle.IDistributedApplicationLifecycleHook
    {
        public Task BeforeStartAsync(DistributedApplicationModel appModel, CancellationToken cancellationToken = default)
        {
            if (!executionContext.IsRunMode)
            {
                return Task.CompletedTask;
            }

            foreach (var resource in appModel.Resources.OfType<DocumentDBServerResource>())
            {
                if (resource.Annotations.OfType<DocumentDBImageSealAnnotation>().Any())
                {
                    continue;
                }

                resource.TryGetContainerImageName(out var reference);

                resource.Annotations.Add(new DocumentDBImageSealAnnotation
                {
                    Reference = reference,
                    Image = ResolveModelImage(resource),
                    BuildOrigin = [.. resource.Annotations.OfType<DockerfileBuildAnnotation>()],
                });
            }

            return Task.CompletedTask;
        }
    }
#pragma warning restore CS0618

    /// <summary>
    /// Rejects an image or build origin that no longer matches what was sealed.
    /// </summary>
    /// <remarks>
    /// This fails closed rather than re-judging the new image, because by the time it can run the
    /// new image is unreachable: DCP has already created the container spec from the sealed
    /// reference, so accepting the change would let the model report a release the container
    /// runtime never launched — in either direction. Silence is the dangerous outcome here, so a
    /// change nothing can act on is reported instead of tolerated.
    /// </remarks>
    private static InvalidOperationException? DescribeImageChangedAfterSeal(IResource resource)
    {
        if (resource.Annotations.OfType<DocumentDBImageSealAnnotation>().LastOrDefault() is not { } seal)
        {
            return null;
        }

        resource.TryGetContainerImageName(out var current);
        var buildOrigin = resource.Annotations.OfType<DockerfileBuildAnnotation>().ToArray();

        if (string.Equals(seal.Reference, current, StringComparison.Ordinal) &&
            HasSameBuildOrigin(seal.BuildOrigin, buildOrigin))
        {
            return null;
        }

        return new InvalidOperationException(
            $"DocumentDB resource '{resource.Name}' changed the container image it will run after " +
            $"this package sealed it. Aspire snapshots the image into the DCP container spec while " +
            $"it prepares the application's containers, which is before endpoints are allocated and " +
            $"before the resource-start event is published, so a change made after that point is " +
            $"judged by the application model but never reaches the container runtime: the model " +
            $"would report one release while the container runs another. " +
            $"Sealed reference: '{Describe(seal.Reference)}'. " +
            $"Current reference: '{Describe(current)}'. " +
            $"Recovery: choose the image while the application model is being built — " +
            $"'.WithImageTag(...)', '.WithImageRegistry(...)', '.WithDockerfile(...)' — rather than " +
            $"from a ResourceEndpointsAllocatedEvent or BeforeResourceStartedEvent subscriber, or " +
            $"from a lifecycle hook that runs after this package's.");

        static string Describe(string? reference) => reference ?? "<none>";
    }

    /// <summary>
    /// Whether the resource still carries the same <see cref="DockerfileBuildAnnotation"/>
    /// instances, in the same order, as when it was sealed.
    /// </summary>
    private static bool HasSameBuildOrigin(DockerfileBuildAnnotation[] sealedOrigin, DockerfileBuildAnnotation[] current)
    {
        if (sealedOrigin.Length != current.Length)
        {
            return false;
        }

        for (var i = 0; i < sealedOrigin.Length; i++)
        {
            if (!ReferenceEquals(sealedOrigin[i], current[i]))
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// The two callbacks that re-apply the hard image floors where nothing is cached: immediately
    /// before a container is created, and while a publish serializes the resource.
    /// </summary>
    private sealed class ImageCompatibilityCheckpointAnnotation : IResourceAnnotation
    {
        /// <summary>
        /// The container-runtime-arguments callback. It contributes nothing and exists only to be
        /// a checkpoint: Aspire never caches these, so it is the one piece of this package's code
        /// that is guaranteed to run on every container creation.
        /// </summary>
        public ContainerRuntimeArgsCallbackAnnotation RuntimeCheckpoint { get; set; } = null!;

        /// <summary>
        /// The manifest publishing callback. It is the publish counterpart of
        /// <see cref="RuntimeCheckpoint"/>: it judges the image while the resource is actually
        /// being serialized, then hands writing on to the callback it displaced.
        /// </summary>
        public ManifestPublishingCallbackAnnotation ManifestCheckpoint { get; set; } = null!;
    }

    /// <summary>
    /// Installs the checkpoints at which the hard image floors are judged against the image the
    /// resource will actually run.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The floors are also subscribed as <see cref="BeforeResourceStartedEvent"/> handlers, which
    /// is where a caller sees them reported while the resource is being started. That is not on its
    /// own sufficient: a subscriber registered after this package runs after those handlers, and
    /// the image they cleared can be replaced before anything reads it — the container's arguments
    /// are gathered afterwards, and a publish raises no per-resource event at all. Aspire caches
    /// each callback's result, so the answer has to be re-checked somewhere it does not: the
    /// container-runtime-arguments callback in a run, and the manifest publishing callback in a
    /// publish.
    /// </para>
    /// <para>
    /// A run additionally seals the image before DCP can snapshot it — see
    /// <see cref="DocumentDBImageSealLifecycleHook"/> — because re-checking is only worth anything
    /// while the answer can still change what runs. The hook is registered with
    /// <c>TryAddLifecycleHook</c>, which deduplicates on service and implementation type, so an
    /// app host calling <c>AddDocumentDB</c> several times still seals exactly once per
    /// application rather than once per resource.
    /// </para>
    /// <para>
    /// The manifest checkpoint has to hold the last position to run at all — the publisher reads
    /// the last <see cref="ManifestPublishingCallbackAnnotation"/> and no other — and hands the
    /// writing on to whatever it displaced, so the manifest is byte-for-byte the one Aspire would
    /// have produced. <see cref="ResourceBuilderExtensions.ExcludeFromManifest{T}"/> stays the
    /// deliberate boundary: a resource that emits nothing has no published image to judge.
    /// </para>
    /// </remarks>
    private static IResourceBuilder<DocumentDBServerResource> InstallImageCompatibilityCheckpoints(
        this IResourceBuilder<DocumentDBServerResource> builder)
    {
#pragma warning disable CS0618 // The lifecycle-hook phase has no eventing equivalent that runs after every BeforeStartEvent subscriber.
        builder.ApplicationBuilder.Services.TryAddLifecycleHook<DocumentDBImageSealLifecycleHook>();
#pragma warning restore CS0618

        var resource = builder.Resource;
        var checkpoints = new ImageCompatibilityCheckpointAnnotation
        {
            RuntimeCheckpoint = new ContainerRuntimeArgsCallbackAnnotation(_ =>
            {
                VerifyImageSeal(resource);
                VerifyImageCompatibility(resource);
                return Task.CompletedTask;
            }),
        };

        checkpoints.ManifestCheckpoint = new ManifestPublishingCallbackAnnotation(async context =>
        {
            VerifyImageCompatibility(resource);

            var displaced = resource.Annotations.OfType<ManifestPublishingCallbackAnnotation>()
                .LastOrDefault(annotation => !ReferenceEquals(annotation, checkpoints.ManifestCheckpoint));

            if (displaced is null)
            {
                await context.WriteContainerAsync(resource).ConfigureAwait(false);
            }
            else if (displaced.Callback is { } callback)
            {
                await callback(context).ConfigureAwait(false);
            }
        });

        resource.Annotations.Add(checkpoints);
        resource.Annotations.Add(checkpoints.RuntimeCheckpoint);
        EstablishManifestCheckpoint(resource, checkpoints);

        // The manifest checkpoint only runs while it is last, and both ExcludeFromManifest() and
        // WithManifestPublishingCallback() append after it. Both phases a publish raises before it
        // serializes anything therefore put it back.
        builder.ApplicationBuilder.Eventing.Subscribe<BeforeStartEvent>((_, _) =>
        {
            EstablishManifestCheckpoint(resource, checkpoints);
            return Task.CompletedTask;
        });

        builder.ApplicationBuilder.Eventing.Subscribe<Publishing.BeforePublishEvent>((_, _) =>
        {
            EstablishManifestCheckpoint(resource, checkpoints);
            return Task.CompletedTask;
        });

        return builder;
    }

    private static void VerifyImageCompatibility(DocumentDBServerResource resource)
    {
        if (DescribeIncompatibleImage(resource) is { } incompatible)
        {
            throw incompatible;
        }
    }

    /// <summary>
    /// Fails the run when the model's image or build origin no longer matches the seal.
    /// </summary>
    /// <remarks>
    /// Called from the uncached container-runtime-arguments checkpoint, which Aspire runs on every
    /// container creation, and from the <see cref="BeforeResourceStartedEvent"/> handlers so the
    /// same failure is also surfaced on the resource's own start path. Outside a run there is no
    /// seal and this does nothing.
    /// </remarks>
    private static void VerifyImageSeal(IResource resource)
    {
        if (DescribeImageChangedAfterSeal(resource) is { } changed)
        {
            throw changed;
        }
    }

    /// <summary>
    /// Puts the manifest checkpoint in the position the manifest publisher reads — last — unless
    /// the resource is excluded from the manifest, in which case it is taken out again.
    /// </summary>
    /// <remarks>
    /// A callback-less annotation is Aspire's <c>ExcludeFromManifest()</c>: the resource is not
    /// written at all, so there is no published image to judge and the exclusion is left in place.
    /// </remarks>
    private static void EstablishManifestCheckpoint(
        DocumentDBServerResource resource,
        ImageCompatibilityCheckpointAnnotation checkpoints)
    {
        var displaced = resource.Annotations.OfType<ManifestPublishingCallbackAnnotation>()
            .LastOrDefault(annotation => !ReferenceEquals(annotation, checkpoints.ManifestCheckpoint));

        resource.Annotations.Remove(checkpoints.ManifestCheckpoint);

        if (displaced is not null && displaced.Callback is null)
        {
            return;
        }

        resource.Annotations.Add(checkpoints.ManifestCheckpoint);
    }

    /// <summary>
    /// Subscribes a <see cref="BeforeResourceStartedEvent"/> handler that throws
    /// <see cref="InvalidOperationException"/> when the resource's effective image tag names a
    /// PostgreSQL backend variant upstream does not publish for that DocumentDB version — see
    /// <see cref="DocumentDBContainerImageTags.MinimumVersionByPgVariant"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Subscribed from <c>AddDocumentDB</c> rather than from <see cref="WithPostgresVersion"/>,
    /// because neither half of the tag is a problem on its own and the documented precedence is
    /// "last call wins": selecting <c>Pg18</c> before <c>V0_114_0</c> is perfectly legitimate,
    /// so only the effective tag at start time can be judged.
    /// </para>
    /// <para>
    /// Same carve-outs as <see cref="SubscribeMinimumPostgresImageGuard"/>: custom images and
    /// tags outside the strict <c>pg{NN}-X.Y.Z</c> grammar are exempt. Unlike that guard this one
    /// is always subscribed, so the exempt paths stay silent rather than warning on every app that
    /// pins a custom image.
    /// </para>
    /// <para>
    /// The subscription reports the failure while the resource is being started, which is where a
    /// caller sees it; it is not what makes the floor hold. A subscriber registered after this
    /// package runs afterwards and can replace the image it cleared, so the same rule — stated
    /// once in <see cref="DescribeUnpublishedPostgresVariant"/> — is applied again at the
    /// checkpoints Aspire never caches. See <see cref="InstallImageCompatibilityCheckpoints"/>.
    /// </para>
    /// </remarks>
    private static IResourceBuilder<DocumentDBServerResource> SubscribeMinimumPgVariantImageGuard(
        this IResourceBuilder<DocumentDBServerResource> builder)
    {
        builder.ApplicationBuilder.Eventing.Subscribe<BeforeResourceStartedEvent>(
            builder.Resource,
            (evt, ct) =>
            {
                VerifyImageSeal(evt.Resource);

                if (DescribeUnpublishedPostgresVariant(evt.Resource, ResolveEffectiveImage(evt.Resource)) is { } incompatible)
                {
                    throw incompatible;
                }

                return Task.CompletedTask;
            });

        return builder;
    }

    /// <summary>
    /// Adds a DocumentDB database to the application model.
    /// </summary>
    /// <remarks>
    /// The database resource inherits the parent server's connection string and appends the database name.
    /// Services should reference the database resource (not the server) via <c>.WithReference(db)</c>.
    /// This resource includes a built-in health check. When this resource is referenced as a dependency
    /// using the <see cref="ResourceBuilderExtensions.WaitFor{T}(IResourceBuilder{T}, IResourceBuilder{IResource})"/>
    /// extension method then the dependent resource will wait until the DocumentDB database responds to ping.
    /// </remarks>
    /// <param name="builder">The DocumentDB server resource builder.</param>
    /// <param name="name">The name of the resource. This name will be used as the connection string name when referenced in a dependency.</param>
    /// <param name="databaseName">The name of the database. If not provided, this defaults to the same value as <paramref name="name"/>.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb");
    /// var ordersDb = server.AddDatabase("orders");
    /// var usersDb = server.AddDatabase("users");
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBDatabaseResource> AddDatabase(this IResourceBuilder<DocumentDBServerResource> builder, [ResourceName] string name, string? databaseName = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(name);

        // Use the resource name as the database name if it's not provided
        databaseName ??= name;

        var DocumentDBDatabase = new DocumentDBDatabaseResource(name, databaseName, builder.Resource);
        builder.Resource.AddDatabase(DocumentDBDatabase);

        string? connectionString = null;

        builder.ApplicationBuilder.Eventing.Subscribe<ConnectionStringAvailableEvent>(DocumentDBDatabase, async (@event, ct) =>
        {
            connectionString = await DocumentDBDatabase.ConnectionStringExpression.GetValueAsync(ct).ConfigureAwait(false)
                ?? throw new DistributedApplicationException($"ConnectionStringAvailableEvent was published for the '{DocumentDBDatabase.Name}' resource but the connection string was null.");
        });

        var healthCheckKey = $"{name}_check";
        // cache the database instance so it is reused on subsequent calls to the health check
        IMongoDatabase? database = null;
        builder.ApplicationBuilder.Services.AddHealthChecks()
            .AddMongoDb(
                _ => database ??=
                    new MongoClient(connectionString ?? throw new InvalidOperationException("Connection string is unavailable"))
                        .GetDatabase(databaseName),
                name: healthCheckKey);

        return builder.ApplicationBuilder
            .AddResource(DocumentDBDatabase)
            .WithHealthCheck(healthCheckKey);
    }

    /// <summary>
    /// Configures the host port that the DocumentDB resource is exposed on instead of using randomly assigned port.
    /// </summary>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="port">The port to bind on the host. If <see langword="null"/> is used random port will be assigned.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithHostPort(10260);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithHostPort(this IResourceBuilder<DocumentDBServerResource> builder, int? port)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEndpoint(DocumentDBServerResource.PrimaryEndpointName, endpoint =>
        {
            endpoint.Port = port;
        });
    }

    /// <summary>
    /// Exposes the PostgreSQL backend coordinator port of the DocumentDB Local container
    /// (default container port <c>9712</c>) as a second endpoint on the resource.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The <c>documentdb-local</c> container bundles a MongoDB-compatible gateway and a
    /// PostgreSQL coordinator listening on separate ports. By default this integration only
    /// publishes the gateway port (<c>10260</c>) and surfaces a <c>mongodb://</c> connection
    /// string. Calling <see cref="WithPostgresEndpoint"/> additionally publishes the
    /// PostgreSQL port so consumers can use psql/Npgsql/etc. directly, and enables
    /// <see cref="DocumentDBServerResource.PostgresConnectionStringExpression"/>.
    /// </para>
    /// <para>
    /// The endpoint uses the same <c>userName</c>/<c>password</c> parameters as the gateway
    /// because the container provisions a single admin user shared by both surfaces.
    /// The default database in the resulting URI is <c>postgres</c>, matching the upstream
    /// entrypoint, which connects with <c>-d postgres</c>.
    /// </para>
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="port">
    /// The host port to bind to. If <see langword="null"/> a random port is assigned.
    /// </param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var documentDB = builder.AddDocumentDB("documentdb")
    ///                         .WithPostgresEndpoint();
    ///
    /// builder.AddProject&lt;Projects.Worker&gt;("worker")
    ///        .WithEnvironment("ConnectionStrings__pg", documentDB.Resource.PostgresConnectionStringExpression);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithPostgresEndpoint(
        this IResourceBuilder<DocumentDBServerResource> builder,
        int? port = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        if (builder.Resource.Annotations.OfType<EndpointAnnotation>()
                .Any(e => e.Name == DocumentDBServerResource.PostgresEndpointName))
        {
            throw new InvalidOperationException(
                $"A PostgreSQL endpoint has already been added to resource '{builder.Resource.Name}'. " +
                $"Call '{nameof(WithPostgresEndpoint)}()' at most once per DocumentDB resource.");
        }

        return builder
            .WithEndpoint(
                port: port,
                targetPort: DefaultPostgresContainerPort,
                scheme: "postgresql",
                name: DocumentDBServerResource.PostgresEndpointName)
            .WithEnvironment(context =>
            {
                // Explicitly opt the upstream entrypoint into accepting external PostgreSQL
                // connections (sets PGOPTIONS=-e -> listen_addresses='*' + permissive pg_hba.conf).
                // Setting this is required so publishing the host port produces a reachable
                // server even on upstream container builds where the entrypoint's default
                // ALLOW_EXTERNAL_CONNECTIONS handling is corrected.
                context.EnvironmentVariables[AllowExternalConnectionsEnvVarName] = "true";
            })
            .SubscribeMinimumPostgresImageGuard();
    }

    /// <summary>
    /// Subscribes a <see cref="BeforeResourceStartedEvent"/> handler that throws
    /// <see cref="InvalidOperationException"/> if the resource's effective container image
    /// tag is older than <see cref="DocumentDBContainerImageTags.MinimumPostgresEndpointVersion"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The handler is registered AFTER endpoint and environment configuration have run,
    /// but executes at run-time via the orchestrator, which honours the documented
    /// "last call wins" precedence: a <c>WithImageTag(...)</c> chained after
    /// <see cref="WithPostgresEndpoint"/> still affects the tag the guard sees.
    /// </para>
    /// <para>
    /// The subscription is what warns about the exempt cases and what reports the failure while
    /// the resource is being started. It is not what makes the floor hold: a subscriber registered
    /// after this package runs afterwards, so the rule — stated once in
    /// <see cref="DescribePostgresEndpointFloor"/> — is applied again at the checkpoints Aspire
    /// never caches, in a run and while a publish serializes the resource alike. See
    /// <see cref="InstallImageCompatibilityCheckpoints"/>.
    /// </para>
    /// <para>
    /// Custom images (anything whose <see cref="ContainerImageAnnotation.Image"/> is not
    /// the curated <see cref="DocumentDBContainerImageTags.Image"/>) are exempt with a
    /// single warning. Tags that do not match the strict <c>pg{NN}-X.Y.Z</c> pattern
    /// (e.g., <c>nightly</c>, <c>pg17-0.112.0-rc.1</c>) are also exempt with a single
    /// warning, so callers pinning custom builds or pre-releases are not surprised by an
    /// unactionable hard failure.
    /// </para>
    /// </remarks>
    private static IResourceBuilder<DocumentDBServerResource> SubscribeMinimumPostgresImageGuard(
        this IResourceBuilder<DocumentDBServerResource> builder)
    {
        // Captured per-resource one-shot flag so unknown-tag / custom-image warnings
        // don't spam on every restart attempt. Hard-failure exceptions are deterministic
        // and intentionally re-thrown on each start attempt. Interlocked guard makes
        // the at-most-once property memory-safe even if a future Aspire orchestrator
        // dispatches BeforeResourceStartedEvent concurrently for the same resource.
        var warningLogged = 0;

        builder.ApplicationBuilder.Eventing.Subscribe<BeforeResourceStartedEvent>(
            builder.Resource,
            (evt, ct) =>
            {
                VerifyImageSeal(evt.Resource);

                var image = ResolveEffectiveImage(evt.Resource);
                if (!image.Exists)
                {
                    // Defensive: AddDocumentDB sets ContainerImageAnnotation eagerly via WithImage.
                    return Task.CompletedTask;
                }

                var logger = TryGetResourceLogger(evt);

                // Custom-image carve-out: only enforce the floor on the curated
                // documentdb-local image. A fork using a different image name
                // (regardless of registry) is assumed to know what it is doing.
                if (!string.Equals(image.Image, DocumentDBContainerImageTags.Image, StringComparison.Ordinal))
                {
                    if (Interlocked.CompareExchange(ref warningLogged, 1, 0) == 0)
                    {
                        logger?.LogWarning(
                            "DocumentDB resource '{ResourceName}' uses custom image '{Image}:{Tag}'. " +
                            "The v{MinVersion} minimum required by WithPostgresEndpoint() for credential parity " +
                            "is NOT enforced on custom images.",
                            evt.Resource.Name,
                            image.Image,
                            image.Tag,
                            DocumentDBContainerImageTags.MinimumPostgresEndpointVersion);
                    }
                    return Task.CompletedTask;
                }

                if (!image.Curated)
                {
                    if (Interlocked.CompareExchange(ref warningLogged, 1, 0) == 0)
                    {
                        logger?.LogWarning(
                            "DocumentDB resource '{ResourceName}' uses image tag '{Tag}', which does not match " +
                            "the curated 'pg{{NN}}-X.Y.Z' pattern. The v{MinVersion} minimum required by " +
                            "WithPostgresEndpoint() for credential parity is NOT enforced on unrecognised tags.",
                            evt.Resource.Name,
                            image.Tag,
                            DocumentDBContainerImageTags.MinimumPostgresEndpointVersion);
                    }
                    return Task.CompletedTask;
                }

                if (DescribePostgresEndpointFloor(evt.Resource, image) is { } incompatible)
                {
                    throw incompatible;
                }

                return Task.CompletedTask;
            });

        return builder;
    }

    private static ILogger? TryGetResourceLogger(BeforeResourceStartedEvent evt)
    {
        // Prefer per-resource logger so the message shows in the Aspire dashboard's
        // resource log pane. Fall back to a general host logger if the service is
        // not registered (shouldn't happen in 13.3.5, but defensive).
        var resourceLoggerService = evt.Services.GetService<ResourceLoggerService>();
        if (resourceLoggerService is not null)
        {
            return resourceLoggerService.GetLogger(evt.Resource);
        }

        var loggerFactory = evt.Services.GetService<ILoggerFactory>();
        return loggerFactory?.CreateLogger("Aspire.Hosting.DocumentDB.WithPostgresEndpoint");
    }

    /// <summary>
    /// Adds a named volume for the data folder to a DocumentDB container resource.
    /// </summary>
    /// <remarks>
    /// The bare DocumentDB container defaults <c>DATA_PATH</c> to <c>/data</c>. Starting with
    /// DocumentDB v0.116-0, the image declares that path as a Docker volume, so omitting this
    /// helper can create an anonymous volume whose lifetime is controlled by the container
    /// runtime. Use this helper when persistence should be explicit and predictable.
    /// This helper mounts the volume at <paramref name="targetPath"/> and sets
    /// <c>DATA_PATH</c> to the same value so DocumentDB writes to the mounted directory.
    /// A persisted data directory may be attached to only one running v0.116-0 container.
    /// </remarks>
    /// <param name="builder">The resource builder.</param>
    /// <param name="name">The name of the volume. Defaults to an auto-generated name based on the application and resource names.</param>
    /// <param name="isReadOnly">A flag that indicates if this is a read-only volume.</param>
    /// <param name="targetPath">The target path inside the container. Defaults to /data to match the container default when this helper is used.</param>
    /// <returns>The <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithDataVolume();
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithDataVolume(
        this IResourceBuilder<DocumentDBServerResource> builder,
        string? name = null,
        bool isReadOnly = false,
        string? targetPath = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        targetPath ??= DefaultMountedDataPath;

        return builder
            .WithVolume(name ?? VolumeNameGenerator.Generate(builder, "data"), targetPath, isReadOnly)
            .WithEnvironment(context =>
            {
                context.EnvironmentVariables[DataPathEnvVarName] = targetPath;
            });
    }

    /// <summary>
    /// Adds a bind mount for the data folder to a DocumentDB container resource.
    /// </summary>
    /// <remarks>
    /// Prefer <see cref="WithDataVolume"/> for most cases. Bind mounts are useful when you need
    /// direct access to the data files on the host filesystem.
    /// The bare DocumentDB container defaults <c>DATA_PATH</c> to <c>/data</c>.
    /// This helper mounts the directory at <c>/data</c> (the container default) and sets
    /// <c>DATA_PATH</c> to the same value so DocumentDB writes to the mounted directory.
    /// </remarks>
    /// <param name="builder">The resource builder.</param>
    /// <param name="source">The source directory on the host to mount into the container.</param>
    /// <param name="isReadOnly">A flag that indicates if this is a read-only mount.</param>
    /// <returns>The <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithDataBindMount("./data/documentdb");
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithDataBindMount(this IResourceBuilder<DocumentDBServerResource> builder, string source, bool isReadOnly = false)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(source);

        const string targetPath = DefaultMountedDataPath;

        return builder
            .WithBindMount(source, targetPath, isReadOnly)
            .WithEnvironment(context =>
            {
                context.EnvironmentVariables[DataPathEnvVarName] = targetPath;
            });
    }

    /// <summary>
    /// Configures the DocumentDB Local container log level.
    /// </summary>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="logLevel">The log level to configure.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithLogLevel(this IResourceBuilder<DocumentDBServerResource> builder, DocumentDBLogLevel logLevel)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[LogLevelEnvVarName] = logLevel.ToEnvironmentValue();
        });
    }

    /// <summary>
    /// Mounts custom initialization scripts into the DocumentDB Local container.
    /// </summary>
    /// <remarks>
    /// The provided directory is bind-mounted at <c>/init_doc_db.d</c>, and the built-in sample data
    /// initialization is implicitly disabled so the mounted scripts are the only initialization source.
    /// DocumentDB v0.116-0 records initialization attempts in the data directory. Scripts run once
    /// for a new volume and are not reapplied when their contents change. A failed partial attempt is
    /// also not automatically retried; use a fresh or reset volume after correcting the scripts.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="source">The source directory on the host to mount into the container.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithInitData(this IResourceBuilder<DocumentDBServerResource> builder, string source)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(source);

        return builder
            .WithBindMount(source, InitDataMountPath, isReadOnly: true)
            .WithEnvironment(context =>
            {
                context.EnvironmentVariables[InitDataPathEnvVarName] = InitDataMountPath;
                context.EnvironmentVariables[SkipInitDataEnvVarName] = "true";
            });
    }

    /// <summary>
    /// Disables the built-in sample data initialization performed by the DocumentDB Local container.
    /// </summary>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithoutSampleData(this IResourceBuilder<DocumentDBServerResource> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[SkipInitDataEnvVarName] = "true";
        });
    }

    /// <summary>
    /// Disables the <c>extended_rum</c> index access method in the DocumentDB Local container
    /// by setting <c>DISABLE_EXTENDED_RUM=true</c>.
    /// </summary>
    /// <remarks>
    /// Available in DocumentDB <c>v0.111-0</c> and later. On older container images the
    /// environment variable is ignored.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithoutExtendedRum(this IResourceBuilder<DocumentDBServerResource> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[DisableExtendedRumEnvVarName] = "true";
        });
    }

    /// <summary>
    /// Disables the DocumentDB Local container's automatic user creation by setting the
    /// upstream <c>CREATE_USER=false</c> environment variable.
    /// </summary>
    /// <remarks>
    /// Use only after a previous run has already created the user in persisted storage
    /// (<see cref="WithDataVolume"/> / <see cref="WithDataBindMount"/>). Setting
    /// <c>CREATE_USER=false</c> on a fresh container will cause init-data steps to fail
    /// authentication and the container entrypoint to exit non-zero. To avoid spurious
    /// init-data runs on subsequent starts, also call <see cref="WithoutSampleData"/>.
    /// <para>
    /// <strong>Important:</strong> The container's init-data scripts (both built-in sample data
    /// and custom scripts mounted via <see cref="WithInitData"/>) authenticate using the
    /// configured credentials. If the user does not exist because creation was skipped,
    /// these scripts will fail and the container will exit. Always pair this method with
    /// <see cref="WithoutSampleData"/> and ensure the user already exists in the persisted data.
    /// </para>
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithoutUserCreation(this IResourceBuilder<DocumentDBServerResource> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[CreateUserEnvVarName] = "false";
        });
    }

    /// <summary>
    /// Mounts a custom TLS certificate and key into the DocumentDB Local container.
    /// </summary>
    /// <remarks>
    /// The certificate and key files are mounted at distinct container paths so that
    /// they do not collide even if their host file names are identical.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="certPath">The certificate file to mount into the container.</param>
    /// <param name="keyPath">The private key file to mount into the container.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithTlsCertificate(this IResourceBuilder<DocumentDBServerResource> builder, string certPath, string keyPath)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(certPath);
        ArgumentException.ThrowIfNullOrEmpty(keyPath);

        var certTargetPath = GetMountedFilePath(certPath, nameof(certPath), "documentdb-cert-");
        var keyTargetPath = GetMountedFilePath(keyPath, nameof(keyPath), "documentdb-key-");

        return builder
            .WithBindMount(certPath, certTargetPath, isReadOnly: true)
            .WithBindMount(keyPath, keyTargetPath, isReadOnly: true)
            .WithEnvironment(context =>
            {
                context.EnvironmentVariables[CertPathEnvVarName] = certTargetPath;
                context.EnvironmentVariables[KeyFileEnvVarName] = keyTargetPath;
            });
    }

    /// <summary>
    /// Enables or disables DocumentDB Local telemetry by setting the <c>ENABLE_TELEMETRY</c>
    /// environment variable.
    /// </summary>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="enabled">Whether telemetry should be enabled.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <remarks>
    /// The <c>ENABLE_TELEMETRY</c> environment variable is not consumed by the DocumentDB gateway
    /// in container image v0.112-0 or later. On those images this method has no observable effect
    /// on the running container. Use <see cref="WithOpenTelemetryMetrics(IResourceBuilder{DocumentDBServerResource}, string?, bool, TimeSpan?, TimeSpan?, string?, string?)"/>
    /// to configure OTLP metrics export.
    /// </remarks>
    [Obsolete(
        "ENABLE_TELEMETRY is not consumed by the DocumentDB gateway in container image v0.112-0 " +
        "or later, so this method has no observable effect on those images. Use " +
        "WithOpenTelemetryMetrics(...) for OTLP metrics. This member is kept for binary " +
        "compatibility and may be removed in a future release.",
        error: false,
        DiagnosticId = "ASPIREDOCDB0001",
        UrlFormat = "https://github.com/microsoft/azure-databases-aspire/blob/main/docs/configuration.md#withtelemetry-obsolete")]
    public static IResourceBuilder<DocumentDBServerResource> WithTelemetry(this IResourceBuilder<DocumentDBServerResource> builder, bool enabled = true)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[EnableTelemetryEnvVarName] = enabled ? "true" : "false";
        });
    }

    /// <summary>
    /// Enables OpenTelemetry metrics export from the DocumentDB gateway via OTLP/gRPC.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Requires container image v0.112-0 or later. This API configures metrics only. The
    /// gateway also supports tracing in v0.116-0 and later, but this package does not yet
    /// expose a typed tracing API.
    /// </para>
    /// <para>
    /// The container default for <c>OTEL_METRICS_ENABLED</c> is <c>false</c>; calling this method
    /// flips it to <c>true</c> unless <paramref name="enabled"/> is explicitly set to <c>false</c>.
    /// </para>
    /// <para>
    /// DocumentDB v0.116-0 ships telemetry values in <c>SetupConfiguration.json</c> that take
    /// precedence over the standard OpenTelemetry environment variables. For the stock Local
    /// image configuration, this method replaces that file when metrics are enabled with the
    /// stable gateway defaults but no telemetry section, so the environment variables documented
    /// below remain authoritative. A caller-supplied <c>CONFIG_DIR</c> remains authoritative and
    /// is not replaced. Aspire publish mode is rejected with an actionable error when metrics are
    /// enabled for the official v0.116-0 image, because not every publisher carries the required
    /// runtime file override. Explicitly disabled metrics remain publishable. Direct AppHost run
    /// mode is supported.
    /// </para>
    /// <para>
    /// Merge semantics across multiple calls on the same builder:
    /// <list type="bullet">
    ///   <item>
    ///     <paramref name="enabled"/> is non-nullable and is therefore written on every call.
    ///     The last call's value wins (defaulting to <c>true</c> when omitted), even if a
    ///     previous call set it to <c>false</c>.
    ///   </item>
    ///   <item>
    ///     All other parameters are nullable; later calls override only the environment variables
    ///     they explicitly set, and values from earlier calls are preserved for parameters left
    ///     at <see langword="null"/>.
    ///   </item>
    /// </list>
    /// </para>
    /// <para>
    /// When <paramref name="endpoint"/> is omitted, the gateway falls back to the standard OTLP/gRPC
    /// default (<c>http://localhost:4317</c>). In an Aspire container scenario, that fallback is
    /// rarely reachable, so an explicit endpoint pointing to your collector is recommended.
    /// </para>
    /// <para>
    /// <paramref name="exportInterval"/> and <paramref name="timeout"/> are written as integer
    /// milliseconds via <see cref="CultureInfo.InvariantCulture"/>. Values smaller than one
    /// millisecond (sub-ms ticks) truncate to <c>0</c>; callers should pass whole-millisecond or
    /// larger granularities.
    /// </para>
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="endpoint">
    /// OTLP/gRPC endpoint of the collector that should receive metrics. When provided, sets
    /// <c>OTEL_EXPORTER_OTLP_METRICS_ENDPOINT</c> (which takes precedence over the generic
    /// <c>OTEL_EXPORTER_OTLP_ENDPOINT</c> per the OpenTelemetry specification). Defaults to
    /// <see langword="null"/> (leave the environment variable unset; gateway falls back to its
    /// own default).
    /// </param>
    /// <param name="enabled">
    /// Whether metrics export is enabled. Sets <c>OTEL_METRICS_ENABLED</c>. Defaults to
    /// <see langword="true"/>: opting into this method clearly indicates the caller wants metrics on.
    /// </param>
    /// <param name="exportInterval">
    /// How often the gateway flushes accumulated metrics to the collector. When provided, sets
    /// <c>OTEL_METRIC_EXPORT_INTERVAL</c> (milliseconds, integer). Must be non-negative.
    /// </param>
    /// <param name="timeout">
    /// Per-export request timeout. When provided, sets <c>OTEL_EXPORTER_OTLP_METRICS_TIMEOUT</c>
    /// (milliseconds, integer). Must be non-negative.
    /// </param>
    /// <param name="serviceName">
    /// Logical service name attached to the metrics. When provided, sets <c>OTEL_SERVICE_NAME</c>.
    /// </param>
    /// <param name="serviceVersion">
    /// Logical service version attached to the metrics. When provided, sets
    /// <c>OTEL_SERVICE_VERSION</c>.
    /// </param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="builder"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="endpoint"/>, <paramref name="serviceName"/>, or <paramref name="serviceVersion"/>
    /// is provided but is empty or whitespace.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <paramref name="exportInterval"/> or <paramref name="timeout"/> is negative.
    /// </exception>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithOpenTelemetryMetrics(
    ///                         endpoint: "http://otel-collector:4317",
    ///                         exportInterval: TimeSpan.FromSeconds(30));
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithOpenTelemetryMetrics(
        this IResourceBuilder<DocumentDBServerResource> builder,
        string? endpoint = null,
        bool enabled = true,
        TimeSpan? exportInterval = null,
        TimeSpan? timeout = null,
        string? serviceName = null,
        string? serviceVersion = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        if (endpoint is not null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(endpoint);
        }

        if (serviceName is not null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(serviceName);
        }

        if (serviceVersion is not null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(serviceVersion);
        }

        if (exportInterval is { } ei)
        {
            ArgumentOutOfRangeException.ThrowIfLessThan(ei, TimeSpan.Zero, nameof(exportInterval));
        }

        if (timeout is { } to)
        {
            ArgumentOutOfRangeException.ThrowIfLessThan(to, TimeSpan.Zero, nameof(timeout));
        }

        EnsureOpenTelemetryEnvironmentConfiguration(builder, enabled);

        return builder.WithEnvironment(context =>
        {
            if (context.ExecutionContext.IsPublishMode &&
                context.Resource is DocumentDBServerResource resource &&
                IsOpenTelemetryCompatibilityEnabled(resource) &&
                RequiresOpenTelemetryEnvironmentConfiguration(resource))
            {
                throw new InvalidOperationException(
                    "WithOpenTelemetryMetrics() cannot publish the official DocumentDB " +
                    "v0.116.0 image because that image requires a runtime " +
                    "SetupConfiguration.json compatibility override that is not supported " +
                    "by every Aspire publisher. Run the AppHost directly, use a custom image " +
                    "with the upstream telemetry configuration fixed, or omit " +
                    "WithOpenTelemetryMetrics() when publishing.");
            }

            context.EnvironmentVariables[OtelMetricsEnabledEnvVarName] = enabled ? "true" : "false";

            if (endpoint is not null)
            {
                context.EnvironmentVariables[OtelExporterOtlpMetricsEndpointEnvVarName] = endpoint;
            }

            if (exportInterval is { } interval)
            {
                context.EnvironmentVariables[OtelMetricExportIntervalEnvVarName] =
                    ((long)interval.TotalMilliseconds).ToString(CultureInfo.InvariantCulture);
            }

            if (timeout is { } timeoutValue)
            {
                context.EnvironmentVariables[OtelExporterOtlpMetricsTimeoutEnvVarName] =
                    ((long)timeoutValue.TotalMilliseconds).ToString(CultureInfo.InvariantCulture);
            }

            if (serviceName is not null)
            {
                context.EnvironmentVariables[OtelServiceNameEnvVarName] = serviceName;
            }
            else if (context.Resource is DocumentDBServerResource serviceNameResource &&
                     IsOpenTelemetryCompatibilityEnabled(serviceNameResource) &&
                     RequiresOpenTelemetryEnvironmentConfiguration(serviceNameResource) &&
                     !context.EnvironmentVariables.ContainsKey(OtelServiceNameEnvVarName))
            {
                context.EnvironmentVariables[OtelServiceNameEnvVarName] = DefaultOpenTelemetryServiceName;
            }

            if (serviceVersion is not null)
            {
                context.EnvironmentVariables[OtelServiceVersionEnvVarName] = serviceVersion;
            }
        });
    }

    private static void EnsureOpenTelemetryEnvironmentConfiguration(
        IResourceBuilder<DocumentDBServerResource> builder,
        bool metricsEnabled)
    {
        var configuration = builder.Resource.Annotations
            .OfType<OpenTelemetryEnvironmentConfigurationAnnotation>()
            .SingleOrDefault();

        if (configuration is not null)
        {
            configuration.MetricsEnabled = metricsEnabled;
            return;
        }

        configuration = new OpenTelemetryEnvironmentConfigurationAnnotation
        {
            MetricsEnabled = metricsEnabled,
        };
        builder.Resource.Annotations.Add(configuration);
        builder.WithContainerFiles(
            DefaultGatewayConfigurationPath,
            (_, _) =>
            {
                IEnumerable<ContainerFileSystemItem> entries =
                    configuration.MetricsEnabled &&
                    RequiresOpenTelemetryEnvironmentConfiguration(builder.Resource)
                        ? [
                            new ContainerFile
                            {
                                Name = "SetupConfiguration.json",
                                Contents = OpenTelemetryEnvironmentConfiguration,
                                Mode = UnixFileMode.UserRead |
                                       UnixFileMode.UserWrite |
                                       UnixFileMode.GroupRead |
                                       UnixFileMode.OtherRead,
                            },
                        ]
                        : [];

                return Task.FromResult(entries);
            });
    }

    private static bool IsOpenTelemetryCompatibilityEnabled(DocumentDBServerResource resource) =>
        resource.Annotations
            .OfType<OpenTelemetryEnvironmentConfigurationAnnotation>()
            .SingleOrDefault()
            ?.MetricsEnabled == true;

    private static bool RequiresOpenTelemetryEnvironmentConfiguration(
        DocumentDBServerResource resource)
    {
        var image = resource.Annotations.OfType<ContainerImageAnnotation>().LastOrDefault();
        if (image is null ||
            !string.Equals(image.Image, DocumentDBContainerImageTags.Image, StringComparison.Ordinal) ||
            !DocumentDBContainerImageTags.TryParseDocumentDBTag(image.Tag, out _, out var version))
        {
            return false;
        }

        return version == OpenTelemetryConfigurationAffectedVersion;
    }


    /// <summary>
    /// Configures the PostgreSQL owner role used by the DocumentDB Local container.
    /// </summary>
    /// <remarks>
    /// The bundled PostgreSQL instance creates the default <c>documentdb</c> role. A custom value
    /// must name a role that already exists, such as the owner of an externally managed
    /// PostgreSQL instance. DocumentDB <c>0.116.0</c> aborts explicitly while creating the
    /// DocumentDB admin user when the configured role does not exist. Earlier images also fail
    /// startup, but only later while waiting for the gateway to start.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="owner">The existing PostgreSQL role used for DocumentDB database operations.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    public static IResourceBuilder<DocumentDBServerResource> WithOwner(this IResourceBuilder<DocumentDBServerResource> builder, string owner)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(owner);

        return builder.WithEnvironment(context =>
        {
            context.EnvironmentVariables[OwnerEnvVarName] = owner;
        });
    }

    /// <summary>
    /// Enables TLS for the DocumentDB connection string. TLS is enabled by default
    /// because the DocumentDB Local container serves TLS on its gateway port using a
    /// self-signed certificate.
    /// Call <c>UseTls(false)</c> to disable TLS if connecting to a non-TLS endpoint.
    /// </summary>
    /// <remarks>
    /// From DocumentDB <c>0.114.0</c> the container's default <c>TLS_MODE=allowTLS</c> accepts
    /// both plain and TLS connections, so <c>UseTls(false)</c> works against the default image.
    /// Container images up to and including <c>0.113.0</c> rejected plain connections regardless
    /// of that setting. Set <c>.WithEnvironment("TLS_MODE", "requireTLS")</c> to make the
    /// container reject plain connections; combining that with <c>UseTls(false)</c> is
    /// self-contradictory and connections will fail.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="useTls">Whether to enable TLS. Defaults to <see langword="true"/>.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// // Disable TLS for a non-TLS endpoint:
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .UseTls(false);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> UseTls(this IResourceBuilder<DocumentDBServerResource> builder, bool useTls = true)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Resource.SetUseTls(useTls);
        return builder;
    }

    /// <summary>
    /// Allows insecure TLS connections by adding <c>tlsInsecure=true</c> to the connection string.
    /// This is enabled by default so the .NET MongoDB driver can connect to the self-signed
    /// certificate used by the DocumentDB Local container.
    /// Call <c>AllowInsecureTls(false)</c> to require valid certificates.
    /// </summary>
    /// <remarks>
    /// The extension uses <c>tlsInsecure=true</c> rather than <c>tlsAllowInvalidCertificates=true</c>
    /// because the .NET MongoDB driver does not fully honor <c>tlsAllowInvalidCertificates</c> for
    /// self-signed certificates and raises <c>UntrustedRoot</c> errors.
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="allowInsecureTls">Whether to allow insecure TLS. Defaults to <see langword="true"/>.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// // Require valid certificates (for example, production with real certs):
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .AllowInsecureTls(false);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> AllowInsecureTls(this IResourceBuilder<DocumentDBServerResource> builder, bool allowInsecureTls = true)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Resource.SetAllowInsecureTls(allowInsecureTls);
        return builder;
    }

    /// <summary>
    /// Pins the DocumentDB version to a specific release known to this build of the package.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The selected version is combined with the currently selected
    /// <see cref="DocumentDBPostgresVersion"/> (default <see cref="DocumentDBPostgresVersion.Pg17"/>)
    /// to produce the container image tag <c>pgN-X.Y.Z</c>.
    /// </para>
    /// <para>
    /// <b>Precedence:</b> for the image tag, the most recent of <see cref="WithDocumentDBVersion"/>,
    /// <see cref="WithPostgresVersion"/>,
    /// <see cref="ContainerResourceBuilderExtensions.WithImage{T}(IResourceBuilder{T}, string, string?)"/>,
    /// and <see cref="ContainerResourceBuilderExtensions.WithImageTag{T}(IResourceBuilder{T}, string)"/>
    /// wins. They all converge on the same single <see cref="ContainerImageAnnotation"/>.
    /// </para>
    /// <para>
    /// This method updates only the image tag. A custom image name or registry configured with
    /// <see cref="ContainerResourceBuilderExtensions.WithImage{T}(IResourceBuilder{T}, string, string?)"/>
    /// or <see cref="ContainerResourceBuilderExtensions.WithImageRegistry{T}(IResourceBuilder{T}, string)"/>
    /// is preserved.
    /// </para>
    /// <para>
    /// To pin to a version not in <see cref="DocumentDBVersion"/> (for example, a brand-new
    /// upstream release this package has not yet been updated to know about), use
    /// <see cref="ContainerResourceBuilderExtensions.WithImageTag{T}(IResourceBuilder{T}, string)"/>
    /// directly with a tag like <c>"pg17-0.999.0"</c>.
    /// </para>
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="version">The DocumentDB version to use.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithDocumentDBVersion(DocumentDBVersion.V0_110_0);
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithDocumentDBVersion(
        this IResourceBuilder<DocumentDBServerResource> builder,
        DocumentDBVersion version)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Resource.SetVersion(version);
        return builder.WithImageTag(builder.Resource.ComputeImageTag());
    }

    /// <summary>
    /// Selects the PostgreSQL backend variant of the <c>documentdb-local</c> container image.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The selected variant is combined with the currently selected
    /// <see cref="DocumentDBVersion"/> (or <see cref="DocumentDBVersions.Latest"/> by default)
    /// to produce the container image tag <c>pgN-X.Y.Z</c>.
    /// </para>
    /// <para>
    /// <b>Precedence:</b> see <see cref="WithDocumentDBVersion"/> — last call wins.
    /// </para>
    /// </remarks>
    /// <param name="builder">The resource builder for DocumentDB.</param>
    /// <param name="pgVersion">The PostgreSQL backend variant to use.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{T}"/>.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="builder"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// Thrown when <paramref name="pgVersion"/> is not a defined member of
    /// <see cref="DocumentDBPostgresVersion"/>. Use a free-form
    /// <see cref="ContainerResourceBuilderExtensions.WithImageTag{T}(IResourceBuilder{T}, string)"/>
    /// call to target an unsupported PG variant.
    /// </exception>
    /// <example>
    /// <code>
    /// var server = builder.AddDocumentDB("documentdb")
    ///                     .WithPostgresVersion(DocumentDBPostgresVersion.Pg16)
    ///                     .WithDocumentDBVersion(DocumentDBVersion.V0_110_0);
    /// // -&gt; image tag "pg16-0.110.0"
    /// </code>
    /// </example>
    public static IResourceBuilder<DocumentDBServerResource> WithPostgresVersion(
        this IResourceBuilder<DocumentDBServerResource> builder,
        DocumentDBPostgresVersion pgVersion)
    {
        ArgumentNullException.ThrowIfNull(builder);

        if (!Enum.IsDefined(pgVersion))
        {
            throw new ArgumentOutOfRangeException(
                nameof(pgVersion),
                pgVersion,
                $"Unsupported PostgreSQL backend variant '{pgVersion}'. " +
                $"Use one of {nameof(DocumentDBPostgresVersion.Pg15)}, " +
                $"{nameof(DocumentDBPostgresVersion.Pg16)}, " +
                $"{nameof(DocumentDBPostgresVersion.Pg17)}, or " +
                $"{nameof(DocumentDBPostgresVersion.Pg18)}, or fall back to a free-form " +
                $"WithImageTag(...) for unsupported variants.");
        }

        builder.Resource.SetPgVersion(pgVersion);
        return builder.WithImageTag(builder.Resource.ComputeImageTag());
    }

    private static string GetMountedFilePath(string source, string paramName, string prefix)
    {
        var fileName = Path.GetFileName(source);

        if (string.IsNullOrEmpty(fileName))
        {
            throw new ArgumentException("The path must include a file name.", paramName);
        }

        return $"/{prefix}{fileName}";
    }
}
