#!/usr/bin/env python3
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
"""Detect new upstream DocumentDB versions and rewrite source files.

What this script does:
  1. Lists GitHub Releases of the upstream `documentdb/documentdb` repository.
     - Filters out drafts and pre-releases.
     - Validates each release tag matches `^v\\d+\\.\\d+-\\d+$`. Non-matching tags are
       logged and skipped (does not crash). Maps `v0.110-0` to `0.110.0`.
  2. Lists tags of the GHCR container image `documentdb/documentdb-local`.
     - Uses the anonymous Bearer token flow (no auth required for public images).
     - Detects all `pgN-` prefixes and warns about any not in REQUIRED_PG_SET.
  3. Computes the intersection of (GH releases) and (GHCR tags), where each version is only
     considered "supported" if every PG variant in REQUIRED_PG_SET (currently {15, 16, 17})
     has a `pgN-X.Y.Z` tag on GHCR.
  4. Parses the auto-generated regions in `src/Aspire.Hosting.DocumentDB/DocumentDBVersion.cs`
     to learn the current curated list.
  5. If the intersection contains versions not in the current list, rewrites the auto-generated
     regions in DocumentDBVersion.cs (only) and replace-in-place updates the auto-generated
     CHANGELOG block.

What this script does NOT do (deliberately):
  - It does not edit `src/Aspire.Hosting.DocumentDB/api/Aspire.Hosting.DocumentDB.cs`. That
    file is the public-API analyzer baseline; auto-editing it would defeat the analyzer's
    purpose as an independent guard. The maintainer reviewing the auto-PR appends new
    `DocumentDBVersion.V0_X_Y` members to that file by hand.
  - It does not bump the NuGet package version. That is a manual step (Git `v*` tag + MinVer).
  - It does not merge anything. The companion workflow opens a PR for human review.

Trust assumption: GHCR tags are mutable. "Version supported" here means "tag exists at the
time of this check", not "image bytes are immutable". Pinning by digest is a future
enhancement.

Exit status: 0 always when invoked normally (success / no-op / new-versions-detected). Non-zero
only on unrecoverable errors (network failures, malformed source files).
"""
from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VERSIONS_FILE = REPO_ROOT / "src" / "Aspire.Hosting.DocumentDB" / "DocumentDBVersion.cs"
CHANGELOG_FILE = REPO_ROOT / "CHANGELOG.md"

GH_OWNER = "documentdb"
GH_REPO = "documentdb"
GHCR_IMAGE_PATH = "documentdb/documentdb/documentdb-local"

REQUIRED_PG_SET: frozenset[int] = frozenset({15, 16, 17})

GH_TAG_RE = re.compile(r"^v(\d+)\.(\d+)-(\d+)$")
GHCR_TAG_RE = re.compile(r"^pg(\d+)-(\d+)\.(\d+)\.(\d+)$")
AUTO_GEN_RE = re.compile(
    r"(// <auto-generated-versions-start>\n)(.*?)(\s*// <auto-generated-versions-end>)",
    re.DOTALL,
)
CHANGELOG_AUTO_GEN_RE = re.compile(
    r"(<!-- auto-generated:documentdb-versions-start -->\n)(.*?)(\n<!-- auto-generated:documentdb-versions-end -->)",
    re.DOTALL,
)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass(frozen=True, order=True)
class SemVer:
    """Semantic version sortable by numeric segment (so 0.9.0 < 0.10.0)."""

    major: int
    minor: int
    patch: int

    def __str__(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}"

    @property
    def enum_member(self) -> str:
        return f"V{self.major}_{self.minor}_{self.patch}"


# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

def _http_get_json_and_link(url: str, headers: dict[str, str] | None = None) -> tuple[object, str | None]:
    req = urllib.request.Request(url, headers=headers or {})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8")), resp.headers.get("Link")


def _http_get_json(url: str, headers: dict[str, str] | None = None) -> object:
    return _http_get_json_and_link(url, headers=headers)[0]


def _get_next_url_from_link_header(current_url: str, link_header: str | None) -> str | None:
    if not link_header:
        return None

    for link in link_header.split(","):
        link = link.strip()
        if not link.startswith("<"):
            continue

        url_end = link.find(">")
        if url_end == -1:
            continue

        target = link[1:url_end]
        for parameter in link[url_end + 1:].split(";"):
            name, separator, value = parameter.strip().partition("=")
            if separator and name.lower() == "rel" and value.strip("\"'").lower() == "next":
                return urllib.parse.urljoin(current_url, target)

    return None


def fetch_github_releases(owner: str, repo: str) -> list[SemVer]:
    """Return non-draft, non-prerelease releases whose tags map to a SemVer."""
    headers: dict[str, str] = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    versions: list[SemVer] = []
    page = 1
    per_page = 100
    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/releases?per_page={per_page}&page={page}"
        data = _http_get_json(url, headers=headers)
        if not isinstance(data, list):
            raise RuntimeError(f"Unexpected releases payload shape: {type(data).__name__}")
        if not data:
            break

        for release in data:
            if release.get("draft") or release.get("prerelease"):
                continue
            tag = release.get("tag_name") or ""
            match = GH_TAG_RE.match(tag)
            if not match:
                print(f"  [skip] release tag does not match expected vMAJOR.MINOR-PATCH: {tag!r}",
                      file=sys.stderr)
                continue
            versions.append(SemVer(int(match[1]), int(match[2]), int(match[3])))

        if len(data) < per_page:
            break
        page += 1

    return versions


def fetch_ghcr_pg_tags(image_path: str) -> dict[SemVer, set[int]]:
    """Return {version: {pg_variants}} for every pgN-X.Y.Z tag on the image."""
    token_url = (
        "https://ghcr.io/token?service=ghcr.io"
        f"&scope=repository:{image_path}:pull"
    )
    token_payload = _http_get_json(token_url)
    if not isinstance(token_payload, dict):
        raise RuntimeError("Unexpected GHCR token payload")
    token = token_payload.get("token") or token_payload.get("access_token")
    if not token:
        raise RuntimeError("GHCR token endpoint returned no token")

    tags: list[object] = []
    list_url: str | None = f"https://ghcr.io/v2/{image_path}/tags/list?n=500"
    headers = {"Authorization": f"Bearer {token}"}
    while list_url:
        payload, link_header = _http_get_json_and_link(list_url, headers=headers)
        if not isinstance(payload, dict):
            raise RuntimeError("Unexpected GHCR tags payload")
        page_tags = payload.get("tags") or []
        if not isinstance(page_tags, list):
            raise RuntimeError("GHCR tags field is not a list")

        tags.extend(page_tags)
        list_url = _get_next_url_from_link_header(list_url, link_header)

    by_version: dict[SemVer, set[int]] = {}
    seen_pg: set[int] = set()
    for tag in tags:
        if not isinstance(tag, str):
            continue
        match = GHCR_TAG_RE.match(tag)
        if not match:
            continue
        pg = int(match[1])
        seen_pg.add(pg)
        version = SemVer(int(match[2]), int(match[3]), int(match[4]))
        by_version.setdefault(version, set()).add(pg)

    unknown = seen_pg - REQUIRED_PG_SET
    if unknown:
        print(f"  [warn] GHCR has unknown PG variants {sorted(unknown)}; "
              "DocumentDBPostgresVersion is not auto-extended.", file=sys.stderr)

    return by_version


# ---------------------------------------------------------------------------
# Source parsing & rewriting
# ---------------------------------------------------------------------------

def parse_known_versions(versions_file: Path) -> dict[SemVer, int]:
    """Return {SemVer: numeric_value} for every member currently in DocumentDBVersion.cs.

    Reads from the FIRST auto-generated region in the file, which is the enum-member region.
    The numeric values must be preserved exactly; this dict is the source of truth used by
    `render_versions_file` to avoid renumbering existing members.
    """
    text = versions_file.read_text(encoding="utf-8")
    matches = AUTO_GEN_RE.findall(text)
    if not matches:
        raise RuntimeError(f"No auto-generated regions found in {versions_file}")
    enum_block = matches[0][1]
    member_re = re.compile(r"V(\d+)_(\d+)_(\d+)\s*=\s*(\d+)", re.MULTILINE)
    out: dict[SemVer, int] = {}
    for m in member_re.finditer(enum_block):
        version = SemVer(int(m[1]), int(m[2]), int(m[3]))
        if version in out:
            raise RuntimeError(f"Duplicate enum member for {version} in {versions_file}")
        out[version] = int(m[4])
    return out


def assign_numeric_values(
    existing: dict[SemVer, int], new_versions: list[SemVer]
) -> dict[SemVer, int]:
    """Return a {SemVer: numeric_value} map that PRESERVES every existing assignment.

    New versions get values strictly greater than `max(existing.values())`, assigned in sort
    order. We deliberately do NOT renumber existing members (binary stability), and we hard-fail
    if asked to assign a value for a version that, in sort order, comes before the current
    maximum -- that would either renumber existing members or assign a higher numeric value to
    a semantically older version, both of which violate the append-only contract. The caller
    (main()) catches this case earlier with a friendlier error; this assertion is the last-line
    defence.
    """
    out = dict(existing)
    if not new_versions:
        return out

    max_known = max(out.keys()) if out else None
    for v in sorted(new_versions):
        if v in out:
            continue
        if max_known is not None and v < max_known:
            raise ValueError(
                f"Refusing to assign a numeric value for {v}: it is older than the current "
                f"max known version {max_known}. Backfilling would either renumber existing "
                f"members or break the append-only invariant."
            )

    next_value = (max(out.values()) + 1) if out else 1
    for v in sorted(new_versions):
        if v in out:
            continue
        out[v] = next_value
        next_value += 1
    return out


def render_versions_file(
    assignments: dict[SemVer, int],
) -> tuple[str, str, str, str]:
    """Build the four auto-generated regions in canonical form.

    `assignments` maps each SemVer to its numeric enum value. Output is sorted ascending by
    SemVer. Numeric values are preserved exactly as supplied (never renumbered).
    """
    if not assignments:
        raise ValueError("Refusing to render an empty version list.")

    versions = sorted(assignments.keys())

    enum_lines: list[str] = []
    enum_lines.append("    // APPEND-ONLY. Numeric values are explicit and frozen for binary stability.")
    enum_lines.append("    // Updated by .github/workflows/check-documentdb-version.yml.")
    enum_lines.append("")
    for v in versions:
        enum_lines.append(f"    /// <summary>DocumentDB <c>{v}</c>.</summary>")
        enum_lines.append(f"    {v.enum_member} = {assignments[v]},")
        enum_lines.append("")
    enum_block = "\n".join(enum_lines).rstrip()

    const_lines: list[str] = []
    const_lines.append("    // Per-version string constants are stable forever once shipped (safe as `const`).")
    const_lines.append("    // Updated by .github/workflows/check-documentdb-version.yml.")
    const_lines.append("")
    for v in versions:
        const_lines.append(f"    /// <summary>DocumentDB version string <c>{v}</c>.</summary>")
        const_lines.append(f'    public const string {v.enum_member} = "{v}";')
        const_lines.append("")
    const_block = "\n".join(const_lines).rstrip()

    list_block = "\n".join(f"        {v.enum_member}," for v in versions)

    switch_block = "\n".join(
        f"        DocumentDBVersion.{v.enum_member} => {v.enum_member},"
        for v in versions
    )

    return enum_block, const_block, list_block, switch_block


def write_versions_file(versions_file: Path, assignments: dict[SemVer, int]) -> None:
    text = versions_file.read_text(encoding="utf-8")
    enum_block, const_block, list_block, switch_block = render_versions_file(assignments)
    blocks = [enum_block, const_block, list_block, switch_block]

    # Replace each auto-generated region in order.
    new_parts: list[str] = []
    cursor = 0
    block_index = 0
    for match in AUTO_GEN_RE.finditer(text):
        start, end = match.span()
        new_parts.append(text[cursor:start])
        replacement = match.group(1) + blocks[block_index] + match.group(3)
        new_parts.append(replacement)
        cursor = end
        block_index += 1

    if block_index != 4:
        raise RuntimeError(
            f"Expected 4 auto-generated regions in {versions_file}, found {block_index}"
        )

    new_parts.append(text[cursor:])
    versions_file.write_text("".join(new_parts), encoding="utf-8")


def update_changelog(changelog_file: Path, new_versions: list[SemVer]) -> None:
    """Replace-in-place the auto-generated DocumentDB versions block in CHANGELOG.md.

    If the marker block does not yet exist, insert it right after the top-level title
    so reruns become idempotent.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body_lines = [
        "## [Unreleased]",
        "",
        "### Added",
        f"- Detected new DocumentDB upstream version(s) on {today}:",
    ]
    for v in new_versions:
        body_lines.append(f"  - {v} (container tags `pg15-{v}`, `pg16-{v}`, `pg17-{v}`)")
    body_lines.append(
        "- These were appended to `DocumentDBVersion` / `DocumentDBVersions`. "
        "The maintainer must also append the new enum members to "
        "`src/Aspire.Hosting.DocumentDB/api/Aspire.Hosting.DocumentDB.cs` before merging."
    )
    body = "\n".join(body_lines)

    text = changelog_file.read_text(encoding="utf-8")
    if CHANGELOG_AUTO_GEN_RE.search(text):
        text = CHANGELOG_AUTO_GEN_RE.sub(
            lambda m: m.group(1) + body + m.group(3),
            text,
            count=1,
        )
    else:
        block = (
            "<!-- auto-generated:documentdb-versions-start -->\n"
            f"{body}\n"
            "<!-- auto-generated:documentdb-versions-end -->\n\n"
        )
        # Insert after the top-level "# Changelog" title and its blank line.
        first_break = text.find("\n\n")
        if first_break == -1:
            text = block + text
        else:
            text = text[: first_break + 2] + block + text[first_break + 2 :]

    changelog_file.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def main() -> int:
    print(f"Checking upstream DocumentDB releases at {datetime.now(timezone.utc).isoformat()}")
    print(f"  REPO_ROOT       = {REPO_ROOT}")
    print(f"  VERSIONS_FILE   = {VERSIONS_FILE}")
    print(f"  REQUIRED_PG_SET = {sorted(REQUIRED_PG_SET)}")

    try:
        gh_versions = fetch_github_releases(GH_OWNER, GH_REPO)
    except (urllib.error.URLError, RuntimeError) as e:
        print(f"ERROR fetching GitHub releases: {e}", file=sys.stderr)
        return 2

    try:
        ghcr_map = fetch_ghcr_pg_tags(GHCR_IMAGE_PATH)
    except (urllib.error.URLError, RuntimeError) as e:
        print(f"ERROR fetching GHCR tags: {e}", file=sys.stderr)
        return 2

    print(f"  GH releases parsed   : {len(gh_versions)}")
    print(f"  GHCR versions parsed : {len(ghcr_map)}")

    # Intersection: must be in BOTH sources, and ALL required pg variants must be present.
    intersected = sorted(
        v for v in gh_versions
        if v in ghcr_map and REQUIRED_PG_SET.issubset(ghcr_map[v])
    )
    if not intersected:
        print("No fully-supported versions found in intersection. Nothing to do.")
        return 0

    known_assignments = parse_known_versions(VERSIONS_FILE)
    known = sorted(known_assignments.keys())
    print(f"  Known to package    : {[str(v) for v in known]}")
    print(f"  Intersection found  : {[str(v) for v in intersected]}")

    # Append-only: never remove a version we already shipped, even if it disappears upstream.
    new_versions = sorted(set(intersected) - set(known))

    if not new_versions:
        print("No new versions detected. Nothing to do.")
        return 0

    print(f"  NEW versions        : {[str(v) for v in new_versions]}")

    # Defensive guard: refuse to "backfill" a version older than the current max known.
    # Numeric enum values for existing members must never shift; assigning a value for an
    # older version after a newer one already exists would be a manual decision.
    max_known = max(known) if known else None
    backfill = [v for v in new_versions if max_known is not None and v < max_known]
    if backfill:
        print(
            f"ERROR refusing to auto-add older version(s) {[str(v) for v in backfill]} "
            f"after the package already shipped {max_known}. Open a manual PR if intentional.",
            file=sys.stderr,
        )
        return 3

    target_assignments = assign_numeric_values(known_assignments, new_versions)

    write_versions_file(VERSIONS_FILE, target_assignments)
    print(f"Updated {VERSIONS_FILE.relative_to(REPO_ROOT)}")

    update_changelog(CHANGELOG_FILE, new_versions)
    print(f"Updated {CHANGELOG_FILE.relative_to(REPO_ROOT)}")

    # Emit a key=value to GITHUB_OUTPUT so the workflow can compose its PR title/body.
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as f:
            f.write(f"new_versions={','.join(str(v) for v in new_versions)}\n")
            f.write(f"all_versions={','.join(str(v) for v in sorted(target_assignments.keys()))}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
