# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
"""Unit tests for eng/scripts/check-documentdb-versions.py.

Run from the repository root with the standard library only (no pip dependencies):

    python -m unittest discover -s eng/scripts/tests

These tests cover the parts of the script that only execute when a *new* upstream version is
detected — in particular that the generated CHANGELOG line derives its container-tag list from
``REQUIRED_PG_SET`` rather than hardcoding pg15/pg16/pg17, which is how it silently drifted when
``pg18`` was introduced in DocumentDB 0.114.0.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import re
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT_PATH = REPO_ROOT / "eng" / "scripts" / "check-documentdb-versions.py"
REAL_VERSIONS_FILE = REPO_ROOT / "src" / "Aspire.Hosting.DocumentDB" / "DocumentDBVersion.cs"
REAL_CHANGELOG_FILE = REPO_ROOT / "CHANGELOG.md"

# Models the expected production layout: the auto-generated block lives at the end of the
# [Unreleased] section, so regenerated notes never land inside a released section.
CHANGELOG_TEMPLATE = (
    "# Changelog\n"
    "\n"
    "## [Unreleased]\n"
    "\n"
    "<!-- auto-generated:documentdb-versions-start -->\n"
    "previous content\n"
    "<!-- auto-generated:documentdb-versions-end -->\n"
    "\n"
    "## [0.114.0] - 2026-07-20\n"
    "\n"
    "hand-written release notes\n"
)


def _load_script():
    """Import the hyphenated script file as a module."""
    spec = importlib.util.spec_from_file_location("check_documentdb_versions", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # Registering the module is required so dataclasses can resolve its __module__.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


script = _load_script()


def _semver(text: str):
    major, minor, patch = (int(part) for part in text.split("."))
    return script.SemVer(major, minor, patch)


def _full_variants(*versions: str) -> dict:
    """GHCR map where every listed version has every required PG variant."""
    return {_semver(v): set(script.REQUIRED_PG_SET) for v in versions}


class FakeRepo:
    """Minimal on-disk copy of the files main() rewrites, isolated in a temp directory.

    Uses a SYNTHETIC version fixture rather than a copy of the real DocumentDBVersion.cs, so
    these tests keep passing after the automation adopts a new version. (Copying the real file
    made expectations like "the next enum value is 7" and "0.115.0 is not yet shipped" true only
    until the next adoption, which would have turned a perfectly good auto-PR red.)
    """

    #: Newest version in the fixture. Adoption candidates are expressed relative to this.
    SHIPPED = "0.101.0"
    #: Numeric enum value of SHIPPED; the next adopted version gets NEXT_VALUE.
    NEXT_VALUE = 3

    VERSIONS_FIXTURE = """// Synthetic fixture; shape mirrors src/Aspire.Hosting.DocumentDB/DocumentDBVersion.cs.
public enum DocumentDBVersion
{
    // <auto-generated-versions-start>
    // APPEND-ONLY. Numeric values are explicit and frozen for binary stability.

    /// <summary>DocumentDB <c>0.100.0</c>.</summary>
    V0_100_0 = 1,

    /// <summary>DocumentDB <c>0.101.0</c>.</summary>
    V0_101_0 = 2,

    // <auto-generated-versions-end>
}

public static class DocumentDBVersions
{
    // <auto-generated-versions-start>
    public const string V0_100_0 = "0.100.0";

    public const string V0_101_0 = "0.101.0";

    // <auto-generated-versions-end>

    private static readonly string[] s_all =
    [
        // <auto-generated-versions-start>
        V0_100_0,
        V0_101_0,
        // <auto-generated-versions-end>
    ];

    internal static string ToVersionString(DocumentDBVersion version) => version switch
    {
        // <auto-generated-versions-start>
        DocumentDBVersion.V0_100_0 => V0_100_0,
        DocumentDBVersion.V0_101_0 => V0_101_0,
        // <auto-generated-versions-end>
        _ => throw new ArgumentOutOfRangeException(nameof(version)),
    };
}
"""

    def __init__(self) -> None:
        self.root = Path(tempfile.mkdtemp())
        self.versions_file = self.root / "src" / "Aspire.Hosting.DocumentDB" / "DocumentDBVersion.cs"
        self.versions_file.parent.mkdir(parents=True)
        self.versions_file.write_text(self.VERSIONS_FIXTURE, encoding="utf-8")
        self.changelog_file = self.root / "CHANGELOG.md"
        self.changelog_file.write_text(CHANGELOG_TEMPLATE, encoding="utf-8")

    def run_main(self, gh_versions, ghcr_map, *, github_actions: bool = False) -> tuple[int, str, str]:
        """Run main() against this fake repo; returns (exit_code, stdout, stderr).

        ``GITHUB_ACTIONS`` is blanked unless a test asks for it, so the workflow-command output
        of `emit_github_annotation` is opt-in: the Python suite itself runs inside Actions, and
        an annotation emitted from a test would show up on the build summary as a real one.
        """
        stdout, stderr = io.StringIO(), io.StringIO()
        env = {"GITHUB_OUTPUT": "", "GITHUB_ACTIONS": "true" if github_actions else ""}
        with mock.patch.object(script, "REPO_ROOT", self.root), \
                mock.patch.object(script, "VERSIONS_FILE", self.versions_file), \
                mock.patch.object(script, "CHANGELOG_FILE", self.changelog_file), \
                mock.patch.object(script, "fetch_github_releases", return_value=gh_versions), \
                mock.patch.object(script, "fetch_ghcr_pg_tags", return_value=ghcr_map), \
                mock.patch.dict(script.os.environ, env), \
                contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            code = script.main()
        return code, stdout.getvalue(), stderr.getvalue()

    def versions_text(self) -> str:
        return self.versions_file.read_text(encoding="utf-8")

    def changelog_text(self) -> str:
        return self.changelog_file.read_text(encoding="utf-8")


class RequiredPgSetTests(unittest.TestCase):
    def test_contains_every_variant_published_upstream(self):
        # pg18 is published upstream from DocumentDB 0.114.0 onwards and mirrors
        # DocumentDBPostgresVersion in src/Aspire.Hosting.DocumentDB/DocumentDBVersion.cs.
        self.assertEqual({15, 16, 17, 18}, set(script.REQUIRED_PG_SET))

    def test_known_ghcr_variants_do_not_trigger_the_unknown_warning(self):
        self.assertEqual(set(), {15, 16, 17, 18} - script.REQUIRED_PG_SET)

    def test_deferred_variants_are_disjoint_from_required(self):
        # DEFERRED_PG_SET exists to acknowledge enum members that the adoption gate deliberately
        # ignores; a variant cannot be both required and deferred.
        self.assertEqual(set(), script.REQUIRED_PG_SET & script.DEFERRED_PG_SET)


class UnknownPgVariantWarningTests(unittest.TestCase):
    """The GHCR scan must treat deferred variants as known, or DEFERRED_PG_SET is decorative."""

    @staticmethod
    def _scan(tags: list[str]) -> tuple[dict, str]:
        """Run fetch_ghcr_pg_tags against a canned GHCR response; returns (result, stderr)."""
        stderr = io.StringIO()
        with mock.patch.object(script, "_http_get_json", return_value={"token": "t"}), \
                mock.patch.object(
                    script, "_http_get_json_and_link", return_value=({"tags": tags}, None)), \
                contextlib.redirect_stderr(stderr):
            result = script.fetch_ghcr_pg_tags("documentdb/documentdb/documentdb-local")
        return result, stderr.getvalue()

    def test_deferred_variant_does_not_produce_unknown_variant_noise(self):
        # The scenario DEFERRED_PG_SET was added for: a maintainer adds Pg19 to the enum and
        # defers it, then upstream starts publishing pg19- tags. Warning here would be false
        # (the member exists) and would recur every single week - the exact noise the pg18 fix
        # removed.
        with mock.patch.object(script, "DEFERRED_PG_SET", frozenset({19})):
            by_version, stderr = self._scan(["pg17-0.115.0", "pg19-0.115.0"])

        self.assertNotIn("unknown PG variants", stderr)
        self.assertEqual({19, 17}, by_version[_semver("0.115.0")] & {17, 19})

    def test_variant_in_neither_set_is_still_reported(self):
        with mock.patch.object(script, "DEFERRED_PG_SET", frozenset({19})):
            _, stderr = self._scan(["pg17-0.115.0", "pg19-0.115.0", "pg99-0.115.0"])

        self.assertIn("unknown PG variants [99]", stderr)


class UpdateChangelogTests(unittest.TestCase):
    TEMPLATE = CHANGELOG_TEMPLATE

    def _write_changelog(self) -> Path:
        path = Path(tempfile.mkdtemp()) / "CHANGELOG.md"
        path.write_text(self.TEMPLATE, encoding="utf-8")
        return path

    def test_tag_list_covers_every_required_pg_variant(self):
        path = self._write_changelog()

        script.update_changelog(path, [script.SemVer(0, 115, 0)])
        text = path.read_text(encoding="utf-8")

        for pg in sorted(script.REQUIRED_PG_SET):
            self.assertIn(f"`pg{pg}-0.115.0`", text)

    def test_tag_list_is_derived_from_required_pg_set(self):
        path = self._write_changelog()

        with mock.patch.object(script, "REQUIRED_PG_SET", frozenset({16, 19})):
            script.update_changelog(path, [script.SemVer(0, 115, 0)])

        text = path.read_text(encoding="utf-8")
        self.assertIn("(container tags `pg16-0.115.0`, `pg19-0.115.0`).", text)
        self.assertNotIn("pg15-0.115.0", text)
        self.assertNotIn("pg17-0.115.0", text)

    def test_replaces_block_in_place_without_touching_handwritten_sections(self):
        path = self._write_changelog()

        script.update_changelog(path, [script.SemVer(0, 115, 0)])
        script.update_changelog(path, [script.SemVer(0, 116, 0)])
        text = path.read_text(encoding="utf-8")

        self.assertEqual(1, text.count("<!-- auto-generated:documentdb-versions-start -->"))
        self.assertNotIn("previous content", text)
        self.assertNotIn("0.115.0", text)
        self.assertIn("`pg18-0.116.0`", text)
        self.assertIn("## [0.114.0] - 2026-07-20", text)
        self.assertIn("hand-written release notes", text)


class BackfillHandlingTests(unittest.TestCase):
    """A1: a backfill candidate must not wedge adoption of newer versions."""

    def test_backfill_candidate_is_skipped_but_newer_version_is_adopted(self):
        # Week 2 of the finding's scenario: a newer version was adopted while a required
        # variant for an older release was still building. Now the older release is complete
        # (a backfill candidate) and must not block adoption of a genuinely newer one.
        repo = FakeRepo()
        gh = [_semver("0.100.5"), _semver("0.102.0")]

        code, stdout, stderr = repo.run_main(gh, _full_variants("0.100.5", "0.102.0"))

        self.assertEqual(0, code)
        self.assertIn("skipping backfill candidate(s) ['0.100.5']", stderr)
        text = repo.versions_text()
        self.assertIn(f"V0_102_0 = {FakeRepo.NEXT_VALUE},", text)
        self.assertNotIn("V0_100_5", text)
        # Existing members keep their numeric values.
        self.assertIn("V0_101_0 = 2,", text)
        self.assertIn("`0.102.0` upstream release detected", repo.changelog_text())

    def test_run_with_only_backfill_candidates_is_a_warned_no_op(self):
        repo = FakeRepo()
        before = repo.versions_text()

        code, stdout, stderr = repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))
        self.assertEqual(0, code)  # sanity: a newer version alone is adopted
        self.assertIn(f"V0_102_0 = {FakeRepo.NEXT_VALUE},", repo.versions_text())

        repo = FakeRepo()
        code, stdout, stderr = repo.run_main([_semver("0.100.5")], _full_variants("0.100.5"))

        self.assertEqual(0, code)
        self.assertIn("skipping backfill candidate(s) ['0.100.5']", stderr)
        self.assertIn("No new versions detected", stdout)
        self.assertEqual(before, repo.versions_text())


class BlockedVersionReportingTests(unittest.TestCase):
    """A2: a version held back on GHCR must be reported, not silent."""

    def test_missing_required_variant_is_reported_on_stderr(self):
        repo = FakeRepo()
        before = repo.versions_text()
        incomplete = sorted(script.REQUIRED_PG_SET)[:-1]
        withheld = max(script.REQUIRED_PG_SET)

        code, stdout, stderr = repo.run_main(
            [_semver("0.102.0")], {_semver("0.102.0"): set(incomplete)}
        )

        self.assertEqual(0, code)
        self.assertIn("0.102.0 blocked", stderr)
        self.assertIn(f"[{withheld}]", stderr)
        self.assertEqual(before, repo.versions_text())

    def test_release_without_any_container_tags_is_reported_on_stderr(self):
        # The common case: the GitHub release is published before (or instead of) the images.
        # Reporting only partial tag sets would leave this failure mode completely silent.
        repo = FakeRepo()
        before = repo.versions_text()

        code, stdout, stderr = repo.run_main([_semver("0.102.0")], _full_variants("0.101.0"))

        self.assertEqual(0, code)
        self.assertIn("0.102.0 blocked", stderr)
        self.assertIn("no pg", stderr)
        self.assertEqual(before, repo.versions_text())

    def test_complete_versions_are_not_reported_as_blocked(self):
        repo = FakeRepo()

        _, _, stderr = repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))

        self.assertNotIn("blocked", stderr)

    def test_already_shipped_versions_are_not_reported_as_blocked(self):
        # Shipped versions are never adoption candidates, so an incomplete (or absent) tag set
        # for them is not a stall.
        repo = FakeRepo()

        _, _, stderr = repo.run_main(
            [_semver("0.100.0"), _semver("0.101.0")], {_semver("0.100.0"): {15}}
        )

        self.assertNotIn("blocked", stderr)


class GitHubAnnotationTests(unittest.TestCase):
    """A2(b): every "cannot adopt yet" path exits 0, so it must annotate the run, not just log."""

    def test_blocked_version_is_annotated(self):
        # Without this the weekly cron is green and unannotated while adoption is stuck, which is
        # indistinguishable from "nothing new upstream" to anyone not reading the log.
        repo = FakeRepo()

        _, stdout, _ = repo.run_main(
            [_semver("0.102.0")], _full_variants("0.101.0"), github_actions=True
        )

        self.assertIn("::warning title=DocumentDB adoption blocked::", stdout)
        self.assertIn("0.102.0 blocked", stdout)

    def test_skipped_backfill_candidate_is_annotated(self):
        repo = FakeRepo()

        _, stdout, _ = repo.run_main(
            [_semver("0.100.5")], _full_variants("0.100.5"), github_actions=True
        )

        self.assertIn("::warning title=DocumentDB backfill candidate skipped::", stdout)

    def test_no_annotation_outside_github_actions(self):
        repo = FakeRepo()

        _, stdout, stderr = repo.run_main([_semver("0.102.0")], _full_variants("0.101.0"))

        self.assertNotIn("::warning", stdout)
        self.assertIn("0.102.0 blocked", stderr)  # the local run still says so on stderr

    def test_a_clean_run_emits_no_annotation(self):
        repo = FakeRepo()

        _, stdout, _ = repo.run_main(
            [_semver("0.102.0")], _full_variants("0.102.0"), github_actions=True
        )

        self.assertNotIn("::warning", stdout)

    def test_annotation_message_is_escaped(self):
        # Raw newlines would truncate a workflow command to its first line.
        with mock.patch.dict(script.os.environ, {"GITHUB_ACTIONS": "true"}):
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                script.emit_github_annotation("warning", "a:title, with commas", "line1\nline2")

        self.assertEqual(
            "::warning title=a%3Atitle%2C with commas::line1%0Aline2\n", stdout.getvalue()
        )


class ObsoleteAttributeTests(unittest.TestCase):
    """A5: DocumentDBVersion's XML docs prescribe [Obsolete] for retiring a member, and that
    attribute has to live inside the auto-generated region. It must neither crash the parser nor
    be dropped by the next rewrite."""

    ATTRIBUTE = '[Obsolete("DocumentDB 0.100.0 is no longer published upstream.")]'

    def _repo_with_obsolete_member(self) -> FakeRepo:
        repo = FakeRepo()
        text = repo.versions_text()
        text = text.replace(
            "    V0_100_0 = 1,", f"    {self.ATTRIBUTE}\n    V0_100_0 = 1,"
        ).replace(
            '    public const string V0_100_0 = "0.100.0";',
            f'    {self.ATTRIBUTE}\n    public const string V0_100_0 = "0.100.0";',
        )
        repo.versions_file.write_text(text, encoding="utf-8")
        return repo

    def test_attribute_line_is_parsed_not_rejected(self):
        repo = self._repo_with_obsolete_member()

        known = script.parse_known_versions(repo.versions_file)

        self.assertEqual({_semver("0.100.0"): 1, _semver("0.101.0"): 2}, known)

    def test_attribute_survives_a_rewrite_that_adopts_a_new_version(self):
        repo = self._repo_with_obsolete_member()

        code, _, _ = repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))

        self.assertEqual(0, code)
        text = repo.versions_text()
        self.assertIn(f"    {self.ATTRIBUTE}\n    V0_100_0 = 1,", text)
        self.assertIn(f'    {self.ATTRIBUTE}\n    public const string V0_100_0 = "0.100.0";', text)
        # ... and only on the member it was attached to.
        self.assertEqual(2, text.count(self.ATTRIBUTE))
        self.assertIn("V0_102_0 = 3,", text)

    def test_multi_line_attribute_is_a_hard_error(self):
        repo = FakeRepo()
        repo.versions_file.write_text(
            repo.versions_text().replace(
                "    V0_100_0 = 1,", '    [Obsolete(\n        "wrapped")]\n    V0_100_0 = 1,'
            ),
            encoding="utf-8",
        )

        with self.assertRaises(RuntimeError) as ctx:
            script.parse_known_versions(repo.versions_file)

        self.assertIn("single line", str(ctx.exception))

    def test_attribute_attached_to_nothing_is_a_hard_error(self):
        repo = FakeRepo()
        repo.versions_file.write_text(
            repo.versions_text().replace(
                "    // <auto-generated-versions-end>\n}",
                f"    {self.ATTRIBUTE}\n    // <auto-generated-versions-end>\n}}",
            ),
            encoding="utf-8",
        )

        with self.assertRaises(RuntimeError) as ctx:
            script.parse_known_versions(repo.versions_file)

        self.assertIn("not attached to any member", str(ctx.exception))

    def test_unrecognized_constant_line_is_a_hard_error(self):
        # The constant region is regenerated wholesale, so a line the parser does not understand
        # is a line that would be silently deleted.
        repo = FakeRepo()
        repo.versions_file.write_text(
            repo.versions_text().replace(
                '    public const string V0_100_0 = "0.100.0";',
                '    public static readonly string V0_100_0 = "0.100.0";',
            ),
            encoding="utf-8",
        )

        with self.assertRaises(RuntimeError) as ctx:
            script.parse_known_versions(repo.versions_file)

        self.assertIn("constant region", str(ctx.exception))


class WriteVersionsFileGuardTests(unittest.TestCase):
    """A3(c): the append-only guard must run against the rendered output, where it can fail."""

    def test_rendering_bug_that_drops_a_member_is_caught_before_writing(self):
        repo = FakeRepo()
        before = repo.versions_text()
        target = {_semver("0.100.0"): 1, _semver("0.101.0"): 2, _semver("0.102.0"): 3}
        real_render = script.render_versions_file

        def drops_the_oldest(assignments, enum_attributes=None, const_attributes=None):
            pruned = {v: n for v, n in assignments.items() if v != _semver("0.100.0")}
            return real_render(pruned, enum_attributes, const_attributes)

        with mock.patch.object(script, "render_versions_file", side_effect=drops_the_oldest):
            with self.assertRaises(RuntimeError) as ctx:
                script.write_versions_file(repo.versions_file, target)

        self.assertIn("V0_100_0 would be removed", str(ctx.exception))
        # The failure must not leave a half-written file behind.
        self.assertEqual(before, repo.versions_text())

    def test_rendering_bug_that_renumbers_a_member_is_caught_before_writing(self):
        repo = FakeRepo()
        before = repo.versions_text()
        target = {_semver("0.100.0"): 1, _semver("0.101.0"): 2, _semver("0.102.0"): 3}
        real_render = script.render_versions_file

        def renumbers(assignments, enum_attributes=None, const_attributes=None):
            shifted = dict(assignments)
            shifted[_semver("0.101.0")] = 9
            return real_render(shifted, enum_attributes, const_attributes)

        with mock.patch.object(script, "render_versions_file", side_effect=renumbers):
            with self.assertRaises(RuntimeError) as ctx:
                script.write_versions_file(repo.versions_file, target)

        self.assertIn("renumbered", str(ctx.exception))
        self.assertEqual(before, repo.versions_text())


class ParseKnownVersionsTests(unittest.TestCase):
    """A3: a degraded parse must crash instead of silently shrinking the shipped enum."""

    def _write_versions_file(self, text: str) -> Path:
        path = Path(tempfile.mkdtemp()) / "DocumentDBVersion.cs"
        path.write_text(text, encoding="utf-8")
        return path

    def test_parses_the_real_versions_file(self):
        known = script.parse_known_versions(REAL_VERSIONS_FILE)

        self.assertIn(_semver("0.114.0"), known)
        self.assertEqual(sorted(known.values()), list(range(1, len(known) + 1)))

    def test_member_without_numeric_value_is_a_hard_error(self):
        original = REAL_VERSIONS_FILE.read_text(encoding="utf-8")
        # V0_113_0 = 5 is shipped, so it is in the file forever (the enum is append-only).
        self.assertIn("V0_113_0 = 5,", original)
        path = self._write_versions_file(original.replace("V0_113_0 = 5,", "V0_113_0,"))

        with self.assertRaises(RuntimeError) as ctx:
            script.parse_known_versions(path)

        self.assertIn("V0_113_0", str(ctx.exception))

    def test_empty_enum_region_is_a_hard_error(self):
        text = (
            "// <auto-generated-versions-start>\n"
            "    // only comments here\n"
            "    // <auto-generated-versions-end>\n"
        )
        path = self._write_versions_file(text)

        with self.assertRaises(RuntimeError):
            script.parse_known_versions(path)


class AssertAppendOnlyTests(unittest.TestCase):
    """A3(b): writing must only ever append."""

    def setUp(self):
        self.existing = {_semver("0.113.0"): 1, _semver("0.114.0"): 2}

    def test_appending_is_allowed(self):
        target = dict(self.existing)
        target[_semver("0.115.0")] = 3

        script.assert_append_only(self.existing, target)  # must not raise

    def test_dropping_a_shipped_member_is_rejected(self):
        target = {_semver("0.114.0"): 2}

        with self.assertRaises(RuntimeError):
            script.assert_append_only(self.existing, target)

    def test_renumbering_a_shipped_member_is_rejected(self):
        target = dict(self.existing)
        target[_semver("0.113.0")] = 9
        target[_semver("0.115.0")] = 3

        with self.assertRaises(RuntimeError) as ctx:
            script.assert_append_only(self.existing, target)

        self.assertIn("renumbered", str(ctx.exception))


class ChangelogMarkerPlacementTests(unittest.TestCase):
    """A4: the rewritten block must live in [Unreleased], never in a released section."""

    def test_repo_changelog_markers_live_in_the_unreleased_section(self):
        text = REAL_CHANGELOG_FILE.read_text(encoding="utf-8")
        match = script.CHANGELOG_AUTO_GEN_RE.search(text)
        self.assertIsNotNone(match, "CHANGELOG.md lost its auto-generated markers.")

        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            misplaced = script.warn_if_markers_outside_unreleased(
                REAL_CHANGELOG_FILE, text, match.start()
            )

        self.assertFalse(misplaced, stderr.getvalue())

    @staticmethod
    def _check(text: str) -> tuple[bool, str]:
        """Run the placement guard over `text`; returns (misplaced, stderr)."""
        path = Path(tempfile.mkdtemp()) / "CHANGELOG.md"
        path.write_text(text, encoding="utf-8")
        match = script.CHANGELOG_AUTO_GEN_RE.search(text)
        assert match is not None

        stdout, stderr = io.StringIO(), io.StringIO()
        # stdout is captured too: the guard emits a workflow-command annotation, which must not
        # leak into the log of the CI job that runs this suite.
        with mock.patch.dict(script.os.environ, {"GITHUB_ACTIONS": ""}), \
                contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            misplaced = script.warn_if_markers_outside_unreleased(path, text, match.start())
        return misplaced, stderr.getvalue()

    def test_markers_inside_a_released_section_are_reported(self):
        misplaced, stderr = self._check(
            "# Changelog\n"
            "\n"
            "## [Unreleased]\n"
            "\n"
            "## [0.114.0] - 2026-07-20\n"
            "\n"
            "<!-- auto-generated:documentdb-versions-start -->\n"
            "body\n"
            "<!-- auto-generated:documentdb-versions-end -->\n"
        )

        self.assertTrue(misplaced)
        self.assertIn("[Unreleased]", stderr)

    def test_missing_unreleased_heading_is_reported(self):
        # A release cut renames "## [Unreleased]" to "## [0.115.0] - <date>". If the heading is
        # not re-added, the markers are now inside a released section - the very bug this guard
        # exists for - so "no [Unreleased] section" must never short-circuit to "placement fine".
        misplaced, stderr = self._check(
            "# Changelog\n"
            "\n"
            "## [0.115.0] - 2026-08-03\n"
            "\n"
            "<!-- auto-generated:documentdb-versions-start -->\n"
            "body\n"
            "<!-- auto-generated:documentdb-versions-end -->\n"
        )

        self.assertTrue(misplaced)
        self.assertIn("[Unreleased]", stderr)

    def test_unreleased_block_does_not_restate_an_already_released_version(self):
        # Moving the markers into [Unreleased] carried the old body along once, so 0.114.0 was
        # listed as a pending addition while a dated ## [0.114.0] section documented it as
        # shipped. Reset the block body when cutting a release.
        text = REAL_CHANGELOG_FILE.read_text(encoding="utf-8")
        block = script.CHANGELOG_AUTO_GEN_RE.search(text).group(2)

        for version in re.findall(r"DocumentDB `([\d.]+)` upstream release detected", block):
            self.assertNotIn(
                f"## [{version}] - ", text,
                f"CHANGELOG.md lists {version} in the [Unreleased] auto-generated block and also "
                f"in a dated '## [{version}]' section.",
            )


class RoundTripTests(unittest.TestCase):
    """The renderer's output must satisfy the (now stricter) parser, or the NEXT run crashes."""

    def test_written_versions_file_is_reparsable_and_rerun_is_a_no_op(self):
        repo = FakeRepo()

        code, _, _ = repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))
        self.assertEqual(0, code)

        known = script.parse_known_versions(repo.versions_file)
        self.assertEqual(
            {_semver("0.100.0"): 1, _semver("0.101.0"): 2, _semver("0.102.0"): FakeRepo.NEXT_VALUE},
            known,
        )

        # Re-running against the same upstream state must change nothing (the workflow reruns
        # on the same auto-PR branch).
        before = repo.versions_text()
        code, stdout, _ = repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))
        self.assertEqual(0, code)
        self.assertIn("No new versions detected", stdout)
        self.assertEqual(before, repo.versions_text())

    def test_every_auto_generated_region_is_rewritten(self):
        # A rewrite that updated the enum but not the const/list/switch regions would ship a
        # version the package cannot resolve at runtime.
        repo = FakeRepo()

        repo.run_main([_semver("0.102.0")], _full_variants("0.102.0"))
        text = repo.versions_text()

        self.assertIn("V0_102_0 = 3,", text)
        self.assertIn('public const string V0_102_0 = "0.102.0";', text)
        self.assertIn("        V0_102_0,", text)
        self.assertIn("DocumentDBVersion.V0_102_0 => V0_102_0,", text)


if __name__ == "__main__":
    unittest.main()
